# 유튜브 인기동영상 데이터
데이터 출처 :https://www.kaggle.com/rsrishav/youtube-trending-video-dataset?select=KR_youtube_trending_data.csv  
데이터 설명 : 유튜브 데일리 인기동영상 (한국)  
dataurl : https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/youtube.csv

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/youtube.csv")
df.head()

,Unnamed: 0,title,channelTitle,categoryId,view_count,likes,dislikes,comment_count,channelId,trending_date2
0,0,[신병] 물자창고,장삐쭈,23,1893473,38249,730,8595,UChbE5OZQ6dRHECsX0tEPEZQ,2021-01-01
1,1,RAIN(비) - 나로 바꾸자 Switch to me (duet with JYP) MV,RAIN's Official Channel,10,2600864,0,0,20129,UCxXgIeE5hxWxHG6dz9Scg2w,2021-01-01
2,2,2020년 제야의 종 온라인 타종행사 | 보신각 현장 행사는 진행하지 않습니다.,서울시 · Seoul,29,347049,3564,120,178,UCZUPZW5idAxYp-Asj__lVAA,2021-01-01
3,3,고기남자의 칠면조 파티,고기남자 MeatMan,26,528458,15372,280,3470,UCT3CumbFIJiW33uq0UI3zlg,2021-01-01
4,4,골목 3mc를 분노하게 만든 마음고생이 심했을 공릉 백반집 사장님의 푸념?! [예능...,스브스밥집,24,494904,3918,111,3142,UCdWgRSfttvDucq4ApcCg5Mw,2021-01-01

##### 1. 인기동영상 제작횟수가 많은 채널 상위 10개명을 출력하라 (날짜기준, 중복포함)

In [3]:
print(*df["channelTitle"].value_counts().head(10).index)

짤툰 파뿌리 SPOTV 런닝맨 - 스브스 공식 채널 엠뚜루마뚜루 : MBC 공식 종합 채널 장삐쭈 BANGTANTV 채널 십오야 이과장 총몇명

##### 2. 논란으로 인기동영상이 된 케이스를 확인하고 싶다. dislikes수가 like 수보다 높은 동영상을 제작한 채널을 모두 출력하라

In [4]:
print(df[df["dislikes"] > df["likes"]].channelTitle.unique())

['핫도그TV' 'ASMR 애정TV' '하얀트리HayanTree' '양팡 YangPang' '철구형 (CHULTUBE)'
 '왜냐맨하우스' '(MUTUBE)와꾸대장봉준' '오메킴TV' '육지담' 'MapleStory_KR'
 'ROAD FIGHTING CHAMPIONSHIP' '사나이 김기훈' '나혼자산다 STUDIO' 'Gen.G esports']

##### ❌ 3. 채널명을 바꾼 케이스가 있는지 확인하고 싶다. channelId의 경우 고유값이므로 이를 통해 채널명을 한번이라도 바꾼 채널의 갯수를 구하여라

In [5]:
# channelId별 channelTitle 고유 개수 확인
result = df.groupby('channelId')['channelTitle'].nunique()

# 채널명을 2개 이상 사용한 경우만 추출
changed = result[result > 1]

# 개수 출력
print(len(changed))

71

##### 4. 일요일에 인기있었던 영상들중 가장많은 영상 종류(categoryId)는 무엇인가?

In [6]:
import datetime as dt

df["trending_date2"] = pd.to_datetime(df["trending_date2"])
df["week_of_day"] = df["trending_date2"].dt.day_name()
print(df[df["week_of_day"] == "Sunday"].value_counts("categoryId").idxmax())

24

##### ❌ 5. 각 요일별 인기 영상들의 categoryId는 각각 몇개 씩인지 하나의 데이터 프레임으로 표현하라

In [7]:
df.groupby(["week_of_day", "categoryId"]).size().reset_index(name="count")

    week_of_day  categoryId  count
0        Friday           1    243
1        Friday           2    120
2        Friday          10    833
3        Friday          15    187
4        Friday          17    633
..          ...         ...    ...
100   Wednesday          25    468
101   Wednesday          26    385
102   Wednesday          27    212
103   Wednesday          28    165
104   Wednesday          29     12

[105 rows x 3 columns]

##### ❌ 6. 댓글의 수로 (comment_count) 영상 반응에 대한 판단을 할 수 있다. viewcount대비 댓글수가 가장 높은 영상을 확인하라 (view_count값이 0인 경우는 제외한다)

In [8]:
# view_count가 0인 경우 제외
temp = df[df["view_count"] != 0].copy()

# 조회수 대비 댓글 비율 계산
temp["ratio"] = temp["comment_count"] / temp["view_count"]

# 비율이 가장 높은 영상 확인
print(temp.loc[temp["ratio"].idxmax()])

Unnamed: 0                                       50830
title             60분 동안 댓글이 달리지 않으면, 영상이 삭제됩니다. (챌린지)
channelTitle                                       팩토리
categoryId                                          24
view_count                                     1214527
likes                                            38246
dislikes                                           528
comment_count                                   196166
channelId                     UCs8R3nVeg0E100H6C8qozgw
trending_date2                     2021-09-02 00:00:00
week_of_day                                   Thursday
ratio                                         0.161516
Name: 50830, dtype: object

##### 7. 댓글의 수로 (comment_count) 영상 반응에 대한 판단을 할 수 있다.viewcount대비 댓글수가 가장 낮은 영상을 확인하라 (view_counts, ratio값이 0인경우는 제외한다.)

In [9]:
temp = temp[temp["ratio"] != 0]
print(temp.loc[temp["ratio"].idxmin()])

Unnamed: 0                                                    46005
title             Join the BTS #PermissiontoDance Challenge only...
channelTitle                                                YouTube
categoryId                                                       27
view_count                                                 46458563
likes                                                             0
dislikes                                                          0
comment_count                                                     1
channelId                                  UCBR8-60-B28hp2BmDPdntcQ
trending_date2                                  2021-08-09 00:00:00
week_of_day                                                  Monday
ratio                                                           0.0
Name: 46005, dtype: object

##### 8. like 대비 dislike의 수가 가장 적은 영상은 무엇인가? (like, dislike 값이 0인경우는 제외한다)

In [10]:
temp = df[(df["dislikes"] != 0) & (df["likes"] != 0)].copy()
temp["ratio"] = temp["dislikes"]/temp["likes"]
print(temp.loc[temp["ratio"].idxmin()])

Unnamed: 0                                                    11477
title             [줌터뷰] *최초공개* 사부작즈🐰🐶의 비공식 이름은 아이라인즈? 꿀조합 티키타카 가...
channelTitle                                      CosmopolitanKorea
categoryId                                                       26
view_count                                                   122354
likes                                                         19104
dislikes                                                         10
comment_count                                                   851
channelId                                  UCVWr5QkOkYupX6fEELMNvuQ
trending_date2                                  2021-02-27 00:00:00
week_of_day                                                Saturday
ratio                                                      0.000523
Name: 11477, dtype: object

##### 9. 가장많은 트렌드 영상을 제작한 채널의 이름은 무엇인가? (날짜기준, 중복포함)

In [11]:
result = df['channelTitle'].value_counts().index[0]

print(result)

짤툰

##### 10. 20회(20일)이상 인기동영상 리스트에 포함된 동영상의 숫자는?

In [12]:
print((df.value_counts("title") >= 20).sum())

41

# ❌ 유튜브 공범컨텐츠 동영상 데이터
데이터 출처 :https://www.kaggle.com/kukuroo3/youtube-episodic-contents-kr(참고, 데이터 수정)  
데이터 설명 : 유튜브 “공범” 컨텐츠 동영상 정보 ( 10분 간격 수집)  
dataurl1 (비디오 정보) = https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/videoInfo.csv  
dataurl2 (참가자 채널 정보)= https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/channelInfo.csv

In [13]:
video = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/videoInfo.csv")
channel = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/channelInfo.csv")
display(video.head())
display(channel.head())

,videopk,viewcnt,likecnt,dislikecnt,favoritecnt,cmcnt,ct,videoname
0,c5JQp6xafqc,1667010,30474,706,0,6587,2021-10-10 15:20:03,공범 EP1
1,c5JQp6xafqc,1669089,30495,707,0,6589,2021-10-10 15:30:03,공범 EP1
2,c5JQp6xafqc,1674759,30522,711,0,6596,2021-10-10 15:40:02,공범 EP1
3,c5JQp6xafqc,1677026,30555,712,0,6604,2021-10-10 15:50:03,공범 EP1
4,c5JQp6xafqc,1681824,30585,713,0,6600,2021-10-10 16:00:03,공범 EP1

,channelid,subcnt,viewcnt,videocnt,ct,channelname
0,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,410238653,736,2021-09-30 03:01:03,꽈뚜룹
1,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,736,2021-09-30 09:01:03,꽈뚜룹
2,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,735,2021-09-30 15:01:03,꽈뚜룹
3,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,737,2021-09-30 21:01:03,꽈뚜룹
4,UCkQCwnkQfgSuPTTnw_Y7v7w,1320000,412531322,737,2021-10-01 03:01:04,꽈뚜룹

##### 11. 각 데이터의 ‘ct’컬럼을 시간으로 인식할수 있게 datatype을 변경하고 video 데이터의 videoname의 각 value 마다 몇개의 데이터씩 가지고 있는지 확인하라

In [ ]:
# datatype 변경
video["ct"] = pd.to_datetime(video["ct"])
channel["ct"] = pd.to_datetime(channel["ct"])

# videoname의 각 value마다 몇 개의 데이터씩 있는지
print(video.value_counts("videoname"))

##### ❌ 12. 수집된 각 video의 가장 최신화 된 날짜의 viewcount값을 출력하라

In [37]:
video.sort_values("ct").drop_duplicates("videoname", keep = "last")

,videopk,viewcnt,likecnt,dislikecnt,favoritecnt,cmcnt,ct,videoname
11543,bK0_3Vbfvs8,1818493,22703,408,0,16949,2021-11-01 15:30:03,공범 EP4
3491,c5JQp6xafqc,3180532,41043,1113,0,7674,2021-11-01 15:30:03,공범 EP1
9263,GygoAk1hDU0,1671294,22719,508,0,12499,2021-11-01 15:30:03,공범 EP3
6695,23QQ1ru9YQg,2199328,25566,763,0,9171,2021-11-01 15:30:03,공범 EP2
13105,hv7FBjskAu0,1503435,19926,421,0,12434,2021-11-01 15:30:04,공범 EP5
14934,AxGKHmXyuAE,1750222,24494,389,0,13025,2021-11-01 15:30:04,공범 EP6
13660,QUjQbgj5IXM,1630200,29335,400,0,18247,2021-11-01 15:30:05,공범 EP7
15200,yZt-h-KcmUE,1289088,25616,3621,0,31663,2021-11-01 15:30:05,공범 EP8

##### 13. Channel 데이터중 2021-10-03일 이후 각 채널의 처음 기록 됐던 구독자 수(subcnt)를 출력하라

In [42]:
print(channel[channel["ct"] >= pd.to_datetime("2021-10-03")].sort_values("ct").drop_duplicates(keep="first")[["subcnt", "channelname"]])

       subcnt      channelname
393    922000           논리왕 전기
266    322000       츄정ChuJeong
139    257000            야전삽짱재
901      7520       김농밀의 농밀한 삶
520     55000  와글와글 WagleWagle
...       ...              ...
1273   469000    곽토리 kwak tori
1146    21100      릴펄 Lilpearl
1019     9060       김농밀의 농밀한 삶
1394    56800    Balming Tiger
130   1400000              꽈뚜룹

[1288 rows x 2 columns]

##### ❌ 14. 각채널의 2021-10-03 03:00:00 ~ 2021-11-01 15:00:00 까지 구독자수 (subcnt) 의 증가량을 구하여라

In [46]:
target = channel[(channel["ct"] >= "2021-10-03 03:00:00") & (channel["ct"] <= "2021-11-01 15:00:00")]

# 채널별 시간순 정렬
target = target.sort_values(['channelname', 'ct'])

# 증가량 계산
result = target.groupby('channelname')['subcnt'].agg(lambda x: x.iloc[-1] - x.iloc[0])

print(result)

channelname
Balming Tiger       2500
곽토리 kwak tori      -2000
김농밀의 농밀한 삶          1540
꽈뚜룹                70000
논리왕 전기            -11000
릴펄 Lilpearl        11000
야전삽짱재              11000
와글와글 WagleWagle        0
조나단                12000
츄정ChuJeong          1000
형사!탐정되다            10300
Name: subcnt, dtype: int64

##### ❌ 15. 각 비디오는 10분 간격으로 구독자수, 좋아요, 싫어요수, 댓글수가 수집된것으로 알려졌다. 공범 EP1의 비디오정보 데이터중 수집간격이 5분 이하, 20분이상인 데이터 구간( 해당 시점 전,후) 의 시각을 모두 출력하라

In [65]:
target = video[video["videoname"].str.contains("공범 EP1")].sort_values("ct").reset_index(drop = True)

# 이전 시각과의 차이 계산(분 단위)
target["diff"] = target["ct"].diff().dt.total_seconds() / 60

# 조건에 해당하는 구간
result = target[(target["diff"] <= 5) | (target["diff"] >= 20)].copy()

# 전 시각 / 후 시각 출력
result["prev_ct"] = target["ct"].shift(1)

print(result[["prev_ct", "ct", "diff"]])

                 prev_ct                  ct        diff
721  2021-10-12 19:20:03 2021-10-13 09:41:37  861.566667
722  2021-10-13 09:41:37 2021-10-13 09:41:37    0.000000
1636 2021-10-19 17:50:02 2021-10-19 18:20:03   30.016667

##### 16. 각 에피소드의 시작날짜(년-월-일)를 에피소드 이름과 묶어 데이터 프레임으로 만들고 출력하라

In [69]:
print(video.sort_values("ct").groupby("videoname").head(1))

           videopk  viewcnt  likecnt  dislikecnt  favoritecnt  cmcnt  \
10     c5JQp6xafqc     6396      680           3            0    226
3496   23QQ1ru9YQg    11153      812           4            0    281
6696   GygoAk1hDU0    10240      735           5            0    241
9264   bK0_3Vbfvs8    23581     1213           6            0    382
11544  hv7FBjskAu0    16777      875           9            0    302
13661  AxGKHmXyuAE    24331     1126           7            0    355
13106  QUjQbgj5IXM    32404     1540          10            0    463
14935  yZt-h-KcmUE    82015     3338          78            0   1438

                       ct videoname
10    2021-10-07 19:10:03    공범 EP1
3496  2021-10-09 19:10:03    공범 EP2
6696  2021-10-14 19:10:04    공범 EP3
9264  2021-10-16 19:10:04    공범 EP4
11544 2021-10-21 19:10:04    공범 EP5
13661 2021-10-23 19:10:04    공범 EP6
13106 2021-10-28 19:10:04    공범 EP7
14935 2021-10-30 19:20:04    공범 EP8

##### ❌ 17. “공범” 컨텐츠의 경우 19:00시에 공개 되는것으로 알려져있다. 공개된 날의 21시의 viewcnt, ct, videoname 으로 구성된 데이터 프레임을 viewcnt를 내림차순으로 정렬하여 출력하라

In [78]:
# 21시 데이터
target = video[video["ct"].dt.hour == 21].sort_values("ct")

# 각 에피소드별 1개만 선택
result = target.groupby("videoname").head(1)

# 필요한 컬럼 + 조회수 내림차순
result = result[["viewcnt", "ct", "videoname"]].sort_values("viewcnt")

print(result)

       viewcnt                  ct videoname
21      117340 2021-10-07 21:00:03    공범 EP1
6707    147183 2021-10-14 21:00:04    공범 EP3
3507    148144 2021-10-09 21:00:03    공범 EP2
11555   201179 2021-10-21 21:00:04    공범 EP5
13672   213899 2021-10-23 21:00:06    공범 EP6
9275    217674 2021-10-16 21:00:04    공범 EP4
13117   252032 2021-10-28 21:00:04    공범 EP7
14945   264029 2021-10-30 21:00:08    공범 EP8

##### 18. video 정보의 가장 최근 데이터들에서 각 에피소드의 싫어요/좋아요 비율을 ratio 컬럼으로 만들고 videoname, ratio로 구성된 데이터 프레임을 ratio를 오름차순으로 정렬하라

In [86]:
lastest = video.sort_values("ct", ascending=False).groupby("videoname").head(1)
lastest["ratio"] = lastest["dislikecnt"] / lastest["likecnt"]
print(lastest[["videoname", "ratio"]].sort_values("ratio", ascending=True))

      videoname     ratio
13660    공범 EP7  0.013636
14934    공범 EP6  0.015881
11543    공범 EP4  0.017971
13105    공범 EP5  0.021128
9263     공범 EP3  0.022360
3491     공범 EP1  0.027118
6695     공범 EP2  0.029844
15200    공범 EP8  0.141357

##### 19. 2021-11-01 00:00:00 ~ 15:00:00까지 각 에피소드별 viewcnt의 증가량을 데이터 프레임으로 만드시오

In [ ]:
target = video[(video["ct"] >= "2021-11-01 00:00:00") & (video["ct"] <= "2021-11-01 15:00:00")].sort_values("ct")
print(target.groupby("videoname")["pe" \
""].agg(lambda x: x.iloc[-1] - x.iloc[0]))

videoname
공범 EP1    13298
공범 EP2    10300
공범 EP3     9927
공범 EP4     9824
공범 EP5    10824
공범 EP6    14141
공범 EP7    26949
공범 EP8    89147
Name: viewcnt, dtype: int64

##### ❌ 20. video 데이터 중에서 중복되는 데이터가 존재한다. 중복되는 각 데이터의 시간대와 videoname 을 구하여라

In [94]:
video[video.index.isin(set(video.index) - set(video.drop_duplicates().index))]

,videopk,viewcnt,likecnt,dislikecnt,favoritecnt,cmcnt,ct,videoname
722,c5JQp6xafqc,2228250,34559,849,0,7191,2021-10-13 09:41:37,공범 EP1
3927,23QQ1ru9YQg,1408005,20484,554,0,8567,2021-10-13 09:41:37,공범 EP2

# ❌ 월드컵 출전선수 골기록 데이터
데이터 출처 :https://www.kaggle.com/darinhawley/fifa-world-cup-goalscorers-19302018(참고, 데이터 수정)  
데이터 설명 : 1930 ~2018년도 월드컵 출전선수 골기록  
data url = https://raw.githubusercontent.com/Datamanim/datarepo/main/worldcup/worldcupgoals.csv

In [95]:
df= pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/worldcup/worldcupgoals.csv")
df.head()

           Player  Goals                Years  Country
0  Miroslav Klose     16  2002-2006-2010-2014  Germany
1         Ronaldo     15       1998-2002-2006   Brazil
2     Gerd Muller     14            1970-1974  Germany
3   Just Fontaine     13                 1958   France
4            Pele     12  1958-1962-1966-1970   Brazil

##### 21. 주어진 전체 기간의 각 나라별 골득점수 상위 5개 국가와 그 득점수를 데이터프레임형태로 출력하라

In [107]:
print(df.groupby("Country")["Goals"].sum().sort_values().head(5).reset_index())

       Country  Goals
0       Angola      1
1      Bolivia      1
2  El Salvador      1
3         Iraq      1
4       Israel      1

##### 22. 주어진 전체기간동안 골득점을 한 선수가 가장 많은 나라 상위 5개 국가와 그 선수 숫자를 데이터 프레임 형식으로 출력하라

In [116]:
# 국가별 득점 선수 수 계산
print(df.groupby("Country")["Player"].nunique().sort_values(ascending=False).head(5).reset_index(name="Player count"))

     Country  Player count
0     Brazil            80
1    Germany            78
2      Italy            60
3  Argentina            59
4     France            58

##### 23. Years 컬럼은 년도 -년도 형식으로 구성되어있고, 각 년도는 4자리 숫자이다. 년도 표기가 4자리 숫자로 안된 케이스가 존재한다. 해당 건은 몇건인지 출력하라

In [128]:
df["Year_list"] = df["Years"].str.split("-")

print(df["Year_list"].apply(lambda x: all(len(i) != 4 for i in x)).sum())

45

##### 24. Q3에서 발생한 예외 케이스를 제외한 데이터프레임을 df2라고 정의하고 데이터의 행의 숫자를 출력하라 (아래 문제부터는 df2로 풀이하겠습니다)

In [165]:
df2 = df[df["Year_list"].apply(lambda x: all(len(i) == 4 for i in x))]
print(len(df2))

1250

##### 25. 월드컵 출전횟수를 나타내는 ‘LenCup’ 컬럼을 추가하고 4회 출전한 선수의 숫자를 구하여라

In [166]:
df['LenCup'] = df['Years'].str.split('-').str.len()
print(len(df2[df2["LenCup"] >= 4]))

16

##### 26. Yugoslavia 국가의 월드컵 출전횟수가 2회인 선수들의 숫자를 구하여라

In [164]:
print(len(df2[(df2["Country"] == "Yugoslavia") & (df2["LenCup"] == 2)]))

7

##### 27. 2002년도에 출전한 전체 선수는 몇 명인가?

In [151]:
print(df2["Year_list"].apply(lambda x: "2002" in x).sum())

156

##### 28. 이름에 ‘carlos’ 단어가 들어가는 선수의 숫자는 몇 명인가? (대, 소문자 구분 x)

In [163]:
print(len(df2[df2['Player'].str.lower().str.contains('carlos')]))

13

##### 29. 월드컵 출전 횟수가 1회뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구인가?

In [179]:
print(df2[df2["LenCup"] == 1].sort_values("Goals").tail(1)["Player"].values)

['Just Fontaine']

##### 30. 월드컵 출전횟수가 1회 뿐인 선수들이 가장 많은 국가는 어디인가?

In [181]:
print(df2[df2.LenCup == 1]['Country'].value_counts().index[0])

Brazil

# 서울시 따릉이 이용정보 데이터
데이터 출처 :https://www.data.go.kr/data/15051872/fileData.do(참고, 데이터 수정)  
데이터 설명 : 서울특별시_공공자전거 시간대별 이용정보  
data url = https://raw.githubusercontent.com/Datamanim/datarepo/main/bicycle/seoul_bi.csv

In [46]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/bicycle/seoul_bi.csv")
df.head()

         대여일자  대여시간  대여소번호 대여구분코드 성별 연령대코드  이용건수    운동량   탄소량     이동거리  사용시간
0  2021-06-01     0   3541    정기권  F  ~10대     1   0.00  0.00     0.00     8
1  2021-06-01     0    765    정기권  F  ~10대     1  27.21  0.35  1526.81    19
2  2021-06-01     0   2637    정기권  F  ~10대     1  41.40  0.37  1608.56    18
3  2021-06-01     0   2919    정기권  F  ~10대     1   0.00  0.00     0.00    75
4  2021-06-01     0    549    정기권  F  ~10대     1  13.04  0.17   731.55     6

##### 31. 대여일자별 데이터의 수를 데이터프레임으로 출력하고, 가장 많은 데이터가 있는 날짜를 출력하라

##### 32. 각 일자의 요일을 표기하고 (‘Monday’ ~’Sunday’) ‘day_name’컬럼을 추가하고 이를 이용하여 각 요일별 이용 횟수의 총합을 데이터 프레임으로 출력하라

##### 33. 각 요일별 가장 많이 이용한 대여소의 이용횟수와 대여소 번호를 데이터 프레임으로 출력하라

##### 34. 나이대별 대여구분 코드의 (일일권/전체횟수) 비율을 구한 후 가장 높은 비율을 가지는 나이대를 확인하라. 일일권의 경우 일일권 과 일일권(비회원)을 모두 포함하라

##### 35. 연령대별 평균 이동거리를 구하여라

##### 36. 연령대 코드가 20대인 데이터를 추출하고,이동거리값이 추출한 데이터의 이동거리값의 평균 이상인 데이터를 추출한다.최종 추출된 데이터를 대여일자, 대여소 번호 순서로 내림차순 정렬 후 1행부터 200행까지의 탄소량의 평균을 소숫점 3째 자리까지 구하여라

##### 37. 6월 7일 ~10대의 “이용건수”의 중앙값은?

##### 38. 평일 (월~금) 출근 시간대(오전 6,7,8시)의 대여소별 이용 횟수를 구해서 데이터 프레임 형태로 표현한 후 각 대여시간별 이용 횟수의 상위 3개 대여소와 이용횟수를 출력하라

##### 39. 이동거리의 평균 이상의 이동거리 값을 가지는 데이터를 추출하여 추출데이터의 이동거리의 표본표준편차 값을 구하여라

##### 40. 남성(‘M’ or ‘m’)과 여성(‘F’ or ‘f’)의 이동거리값의 평균값을 구하여라

# 전세계 행복도 지표 데이터
데이터 출처 :https://www.kaggle.com/unsdsn/world-happiness(참고, 데이터 수정)  
데이터 설명 : 전세계 행복도 지표 조사  
data url = https://raw.githubusercontent.com/Datamanim/datarepo/main/happy2/happiness.csv

In [57]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/happy2/happiness.csv", encoding = "utf-8")
df

,행복랭킹,나라명,점수,상대GDP,사회적지원,행복기대치,선택의 자유도,관대함,부패에 대한인식,년도
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,2019
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,2019
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,2019
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,2019
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,2019
...,...,...,...,...,...,...,...,...,...,...
307,152,Yemen,3.355,0.442,1.073,0.343,0.244,0.083,0.064,2018
308,153,Tanzania,3.303,0.455,0.991,0.381,0.481,0.270,0.097,2018
309,154,South Sudan,3.254,0.337,0.608,0.177,0.112,0.224,0.106,2018
310,155,Central African Republic,3.083,0.024,0.000,0.010,0.305,0.218,0.038,2018
311,156,Burundi,2.905,0.091,0.627,0.145,0.065,0.149,0.076,2018

##### 41. 데이터는 2018년도와 2019년도의 전세계 행복 지수를 표현한다. 각년도의 행복랭킹 10위를 차지한 나라의 행복점수의 평균을 구하여라

##### 42. 데이터는 2018년도와 2019년도의 전세계 행복 지수를 표현한다. 각년도의 행복랭킹 50위이내의 나라들의 각각의 행복점수 평균을 데이터프레임으로 표시하라

##### 43. 2018년도 데이터들만 추출하여 행복점수와 부패에 대한 인식에 대한 상관계수를 구하여라

##### 44. 2018년도와 2019년도의 행복랭킹이 변화하지 않은 나라명의 수를 구하여라

##### 45. ❌ 2019년도 데이터들만 추출하여 각변수간 상관계수를 구하고 내림차순으로 정렬한 후 상위 5개를 데이터 프레임으로 출력하라. 컬럼명은 v1,v2,corr으로 표시하라

##### 46. ❌ 각 년도별 하위 행복점수의 하위 5개 국가의 평균 행복점수를 구하여라

##### 47. 2019년 데이터를 추출하고 해당데이터의 상대 GDP 평균 이상의 나라들과 평균 이하의 나라들의 행복점수 평균을 각각 구하고 그 차이값을 출력하라

##### 48. ❌ 각 년도의 부패에 대한 인식을 내림차순 정렬했을때 상위 20개 국가의 부패에 대한 인식의 평균을 구하여라

##### 49. 2018년도 행복랭킹 50위 이내에 포함됐다가 2019년 50위 밖으로 밀려난 국가의 숫자를 구하여라

##### 50. ❌ 2018년,2019년 모두 기록이 있는 나라들 중 년도별 행복점수가 가장 증가한 나라와 그 증가 수치는?

# 지역구 에너지 소비량 데이터2
데이터 출처 : https://archive.ics.uci.edu/ml/datasets/Power+consumption+of+Tetouan+city (참고, 데이터 수정)  
데이터 설명 : 기온, 습도,바람풍속에 따른 도시의 3개 지역구의 에너지 소비량  
data url = https://raw.githubusercontent.com/Datamanim/datarepo/main/consum/Tetuan City power consumption.csv

In [69]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/consum/Tetuan%20City%20power%20consumption.csv")
df.head()

,DateTime,Temperature,Humidity,Wind Speed,general diffuse flows,diffuse flows,Zone 1 Power Consumption,Zone 2 Power Consumption,Zone 3 Power Consumption
0,1/1/2017 0:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386
1,1/1/2017 0:10,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434
2,1/1/2017 0:20,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373
3,1/1/2017 0:30,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711
4,1/1/2017 0:40,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964

##### 51. DateTime컬럼을 통해 각 월별로 몇개의 데이터가 있는지 데이터 프레임으로 구하여라

##### 52. 3월달의 각 시간대별 온도의 평균들 중 가장 낮은 시간대의 온도를 출력하라

##### 53. 3월달의 각 시간대별 온도의 평균들 중 가장 높은 시간대의 온도를 출력하라

##### 54. Zone 1 Power Consumption 컬럼의 value값의 크기가 Zone 2 Power Consumption 컬럼의 value값의 크기보다 큰 데이터들의 Humidity의 평균을 구하여라

##### 55. 각 zone의 에너지 소비량의 상관관계를 구해서 데이터 프레임으로 표기하라

##### 56. Temperature의 값이 10미만의 경우 A, 10이상 20미만의 경우 B,20이상 30미만의 경우 C, 그 외의 경우 D라고 할때 각 단계의 데이터 숫자를 구하여라

##### 57. 6월 데이터중 12시의 Temperature의 표준편차를 구하여라

##### 58. 6월 데이터중 12시의 Temperature의 분산을 구하여라

##### 59. Temperature의 평균이상의 Temperature의 값을 가지는 데이터를 Temperature를 기준으로 정렬 했을때 4번째 행의 Humidity 값은?

##### 60. Temperature의 중간값 이상의 Temperature의 값을 가지는 데이터를Temperature를 기준으로 정렬 했을때 4번째 행의 Humidity 값은?

# 포켓몬 정보 데이터
데이터 출처 : https://www.kaggle.com/abcsds/pokemon (참고, 데이터 수정)  
데이터 설명 : 포켓몬 정보  
data url = https://raw.githubusercontent.com/Datamanim/datarepo/main/pok/Pokemon.csv

In [80]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/pok/Pokemon.csv")
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

##### 61. Legendary 컬럼은 전설포켓몬 유무를 나타낸다.전설포켓몬과 그렇지 않은 포켓몬들의 HP평균의 차이를 구하여라

##### 62. Type 1은 주속성 Type 2 는 부속성을 나타낸다. 가장 많은 부속성 종류는 무엇인가?

##### 63. 가장 많은 Type 1 의 종의 평균 Attack 을 평균 Defense로 나눈값은?

##### 64. 포켓몬 세대(Generation) 중 가장많은 Legendary를 보유한 세대는 몇세대인가?

##### 65. ‘HP’, ‘Attack’, ‘Defense’, ‘Sp. Atk’, ‘Sp. Def’, ‘Speed’ 간의 상관 계수중 가장 절댓값이 큰 두 변수와 그 값을 구하여라

##### 66. 각 Generation의 Attack으로 오름차순 정렬시 상위 3개 데이터들(18개)의 Attack의 전체 평균을 구하여라

##### 67. 각 Generation의 Attack으로 내림차순 정렬시 상위 5개 데이터들(30개)의 Attack의 전체 평균을 구하여라

##### 68. 가장 흔하게 발견되는 (Type1 , Type2) 의 쌍은 무엇인가?

##### 69. 한번씩만 존재하는 (Type1 , Type2)의 쌍의 갯수는 몇개인가?

##### 70. ❌ 한번씩만 존재하는 (Type1 , Type2)의 쌍을 각 세대(Generation)은 각각 몇개씩 가지고 있는가?

# 대한민국 체력장 데이터
데이터 출처 : 국민체육진흥공단 (문화 빅데이터플랫폼) (참고, 데이터 수정)  
데이터 설명 : 대한민국 국민 체력장 평가  
data url = https://raw.githubusercontent.com/Datamanim/datarepo/main/body/body.csv

##### 71. 전체데이터의 수축기혈압(최고) - 이완기혈압(최저)의 평균을 구하여라

##### 72. 50~59세의 신장평균을 구하여라

##### 73. 연령대 (20~29 : 20대 …) 별 인원수를 구하여라

##### 74. 연령대 (20~29 : 20대 …) 별 등급의 숫자를 데이터 프레임으로 표현하라

##### 75. 남성 중 A등급과 D등급의 체지방률 평균의 차이(큰 값에서 작은 값의 차)를 구하여라

##### 76. 여성 중 A등급과 D등급의 체중의 평균의 차이(큰 값에서 작은 값의 차)를 구하여라

##### 77. bmi는 자신의 몸무게(kg)를 키의 제곱(m)으로 나눈값이다. 데이터의 bmi 를 구한 새로운 컬럼을 만들고 남성의 bmi 평균을 구하여라

##### 78. bmi보다 체지방율이 높은 사람들의 체중평균을 구하여라

##### 79. 남성과 여성의 악력 평균의 차이를 구하여라

##### 80. 남성과 여성의 교차윗몸일으키기 횟수의 평균의 차이를 구하여라

# 기온 강수량 데이터
데이터 출처 : https://data.kma.go.kr/cmmn/static/staticPage.do?page=intro  
데이터 설명 : 2020년도 이화동(서울) , 수영동(부산)의 시간단위의 기온과 강수량  
데이터 url : https://raw.githubusercontent.com/Datamanim/datarepo/main/weather/weather2.csv

In [104]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/weather/weather2.csv")
df

                     time  이화동강수  이화동기온  수영동강수  수영동기온
0     2020-01-01 00:00:00    0.1   -3.9    0.0    2.5
1     2020-01-01 01:00:00    0.0   -3.1    0.0    3.4
2     2020-01-01 02:00:00    0.0   -1.8    0.0    3.8
3     2020-01-01 03:00:00    0.0   -0.8    0.0    4.6
4     2020-01-01 04:00:00    0.0   -0.1    0.0    5.1
...                   ...    ...    ...    ...    ...
8779  2020-12-31 19:00:00    0.0   -9.5    0.0   -4.5
8780  2020-12-31 20:00:00    0.0   -9.5    0.0   -5.0
8781  2020-12-31 21:00:00    0.0   -9.3    0.0   -6.5
8782  2020-12-31 22:00:00    0.0   -9.2    0.0   -4.6
8783  2020-12-31 23:00:00    0.0   -7.8    0.0   -0.2

[8784 rows x 5 columns]

##### 81. 여름철(6월,7월,8월) 이화동이 수영동보다 높은 기온을 가진 시간대는 몇개인가?

##### 82. 이화동과 수영동의 최대강수량의 시간대를 각각 구하여라

# 서비스 이탈예측 데이터
데이터 출처 : https://www.kaggle.com/shubh0799/churn-modelling 에서 변형  
데이터 설명 : 고객의 신상정보 데이터를 통한 회사 서비스 이탈 예측 (종속변수 : Exited)  
Data url : https://raw.githubusercontent.com/Datamanim/datarepo/main/churn/train.csv

In [107]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/churn/train.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,6842,15793491,Cherkasova,714,Germany,Male,26,3,119545.48,2,1,0,65482.94,0
1,8963,15607874,Keane,687,France,Male,38,0,144450.58,1,0,1,137276.83,0
2,7047,15737627,Rivero,589,Germany,Female,20,2,121093.29,2,1,0,3529.72,0
3,7503,15697844,Whitehouse,721,Spain,Female,32,10,0.00,1,1,0,136119.96,1
4,3439,15722404,Carpenter,445,France,Female,30,3,0.00,2,1,1,127939.19,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7994,1607,15714080,Goliwe,566,Germany,Female,40,2,97001.36,2,1,0,154486.01,0
7995,7744,15741643,Chiang,777,Germany,Male,35,7,122917.69,1,1,1,76169.68,0
7996,4231,15566660,Cole,670,France,Female,41,10,0.00,3,1,0,81602.02,0
7997,8870,15733597,Y?an,669,France,Female,41,0,150219.41,2,0,0,107839.03,0
7998,523,15595766,Watts,527,Spain,Male,37,5,93722.73,2,1,1,139093.73,0

##### 83. ❌ 남성 이탈(Exited)이 가장 많은 국가(Geography)는 어디이고 이탈 인원은 몇명인가?

##### 84. 카드를 소유(HasCrCard ==1)하고 있으면서 활성멤버(IsActiveMember ==1) 인 고객들의 평균 나이를 소숫점이하 4자리까지 구하여라

##### 85. Balance 값이 중간값 이상을 가지는 고객들의 CreditScore의 표준편차를 소숫점이하 3자리까지 구하여라

# 성인 건강검진 데이터
데이터 출처 :https://www.data.go.kr/data/15007122/fileData.do (참고, 데이터 수정)  
데이터 설명 : 2018년도 성인의 건강검 진데이터 (흡연상태 1- 흡연, 0-비흡연 )  
데이터 url : https://raw.githubusercontent.com/Datamanim/datarepo/main/smoke/train.csv

In [111]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/smoke/train.csv")
df

,성별코드,연령대코드(5세단위),신장(5Cm단위),체중(5Kg단위),허리둘레,시력(좌),시력(우),청력(좌),청력(우),수축기혈압,...,혈색소,요단백,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태,구강검진수검여부,치아우식증유무,치석
0,F,55,145,55,73.0,0.7,0.5,1.0,1.0,129.0,...,12.9,1.0,0.9,172.0,209.0,15.0,0,Y,0.0,Y
1,M,40,180,55,74.0,1.5,1.5,1.0,1.0,102.0,...,15.6,1.0,0.8,30.0,19.0,23.0,1,Y,0.0,Y
2,F,55,150,50,72.0,1.0,0.2,1.0,1.0,116.0,...,14.1,1.0,1.0,31.0,19.0,10.0,0,Y,0.0,N
3,M,40,170,85,89.0,1.0,0.8,1.0,1.0,124.0,...,16.7,1.0,1.0,26.0,38.0,108.0,1,Y,1.0,Y
4,F,40,155,45,62.0,0.5,1.0,1.0,1.0,127.0,...,12.9,1.0,0.7,20.0,11.0,13.0,0,Y,0.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44548,F,60,145,50,87.0,1.0,1.0,1.0,1.0,140.0,...,12.3,1.0,0.5,24.0,32.0,15.0,0,Y,1.0,Y
44549,M,40,175,75,88.0,1.5,1.2,1.0,1.0,139.0,...,15.3,1.0,0.8,62.0,106.0,49.0,1,Y,0.0,Y
44550,F,60,150,55,82.0,0.9,0.9,1.0,1.0,124.0,...,14.1,1.0,0.5,38.0,34.0,26.0,0,Y,0.0,Y
44551,M,40,170,50,69.0,0.4,1.2,1.0,1.0,117.0,...,14.2,1.0,0.9,22.0,17.0,55.0,1,Y,0.0,N
44552,F,40,155,50,72.5,1.0,1.0,1.0,1.0,109.0,...,11.7,1.0,0.6,16.0,10.0,7.0,0,Y,0.0,N

##### 86. 수축기혈압과 이완기 혈압기 수치의 차이를 새로운 컬럼(‘혈압차’) 으로 생성하고, 연령대 코드별 각 그룹 중 ‘혈압차’ 의 분산이 5번째로 큰 연령대 코드를 구하여라

##### 87. ❌ 비만도를 나타내는 지표인 WHtR는 허리둘레 / 키로 표현한다. 일반적으로 0.58이상이면 비만으로 분류한다. 데이터중 WHtR 지표상 비만인 인원의 남/여 비율을 구하여라

# 자동차 보험가입 예측데이터
데이터 출처 :https://www.kaggle.com/anmolkumar/health-insurance-cross-sell-prediction(참고, 데이터 수정)  
데이터 설명 : 자동차 보험 가입 예측  
Data url : https://raw.githubusercontent.com/Datamanim/datarepo/main/insurance/train.csv

In [114]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/insurance/train.csv")
df

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,188957,Female,25,1,17.0,1,< 1 Year,No,38785.0,152.0,59,0
1,275631,Male,20,1,22.0,0,< 1 Year,No,2630.0,160.0,113,0
2,329036,Female,40,1,41.0,0,1-2 Year,Yes,33165.0,124.0,188,0
3,227288,Female,28,1,30.0,1,< 1 Year,No,29038.0,152.0,233,0
4,300441,Female,50,1,28.0,0,1-2 Year,Yes,31325.0,124.0,258,0
...,...,...,...,...,...,...,...,...,...,...,...,...
304882,351529,Male,75,1,33.0,0,1-2 Year,Yes,32412.0,26.0,296,1
304883,287917,Male,57,1,28.0,1,1-2 Year,No,44602.0,52.0,135,0
304884,21023,Female,40,1,35.0,0,1-2 Year,Yes,38779.0,26.0,293,0
304885,67340,Male,24,1,41.0,0,< 1 Year,Yes,26669.0,152.0,29,0
304886,127164,Female,22,1,50.0,1,< 1 Year,No,35063.0,152.0,184,0

##### 88. Vehicle_Age 값이 2년 이상인 사람들만 필터링 하고 그중에서 Annual_Premium 값이 전체 데이터의 중간값 이상인 사람들을 찾고, 그들의 Vintage값의 평균을 구하여라

##### 89. ❌ vehicle_age에 따른 각 성별(gender)그룹의 Annual_Premium값의 평균을 구하여 아래 테이블과 동일하게 구현하라

# ❌ 핸드폰 가격 예측데이터
데이터 출처 :https://www.kaggle.com/iabhishekofficial/mobile-price-classification?select=train.csv(참고, 데이터 수정)  
데이터 설명 : 핸드폰 가격예측 (price_range컬럼 0(저렴) ~3(매우비쌈) 범위 )  
Data url https://raw.githubusercontent.com/Datamanim/datarepo/main/mobile/train.csv

In [117]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/mobile/train.csv")
df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

##### 90. price_range 의 각 value를 그룹핑하여 각 그룹의 n_cores 의 빈도가 가장높은 value와 그 빈도수를 구하여라

##### 91. price_range 값이 3인 그룹에서 상관관계가 2번째로 높은 두 컬럼과 그 상관계수를 구하여라

# 비행탑승 경험 만족도 데이터
데이터 출처 :https://www.kaggle.com/teejmahal20/airline-passenger-satisfaction?select=train.csv (참고, 데이터 수정)  
데이터 설명 : 비행탑승 경험 만족도 (satisfaction 컬럼 : ‘neutral or dissatisfied’ or satisfied ) (83123, 24) shape  
Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/train.csv

In [120]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/train.csv")
df

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,55882,Male,Loyal Customer,42,Business travel,Business,473,1,1,3,...,5,5,5,5,3,5,3,3,0.0,satisfied
1,31906,Female,Loyal Customer,31,Business travel,Business,3271,4,4,4,...,3,3,5,5,3,4,3,1,5.0,satisfied
2,85481,Male,Loyal Customer,51,Personal Travel,Eco,214,5,0,5,...,3,4,4,4,4,4,3,2,0.0,satisfied
3,102134,Male,Loyal Customer,44,Business travel,Business,3097,1,1,3,...,4,4,4,4,3,4,5,0,0.0,satisfied
4,31580,Male,Loyal Customer,33,Business travel,Business,3286,1,1,1,...,4,2,5,2,5,1,4,0,0.0,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83118,9745,Male,Loyal Customer,39,Business travel,Business,3706,1,1,1,...,4,4,4,4,2,4,4,1,0.0,satisfied
83119,5190,Male,Loyal Customer,49,Business travel,Business,295,0,0,0,...,1,1,1,1,4,1,4,0,0.0,satisfied
83120,41381,Female,Loyal Customer,62,Business travel,Business,1914,3,5,5,...,3,3,3,3,3,3,3,64,48.0,neutral or dissatisfied
83121,79829,Female,Loyal Customer,53,Business travel,Business,3681,2,2,2,...,4,4,4,4,3,4,3,45,21.0,satisfied
83122,84734,Female,Loyal Customer,51,Business travel,Business,2943,2,2,2,...,4,4,4,4,5,4,3,0,0.0,satisfied

##### 92. Arrival Delay in Minutes 컬럼이 결측치인 데이터들 중 ‘neutral or dissatisfied’ 보다 ‘satisfied’의 수가 더 높은 Class는 어디 인가?

# 수질 음용성 여부 데이터
데이터 출처 :https://www.kaggle.com/adityakadiwal/water-potability  
데이터 설명 : 수질 음용성 여부 (Potablillity 컬럼 : 0 ,1 )  
Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/waters/train.csv

In [122]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/waters/train.csv")
df

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,7.918150,214.186611,23823.492888,7.290878,341.173322,411.424483,19.585002,25.057375,4.028958,0
1,5.422446,205.266080,18542.957451,5.491963,306.702227,382.080129,10.504023,67.493450,2.911751,1
2,7.341547,187.672402,21273.457066,7.784003,NaN,332.084293,16.842334,55.019151,4.025644,0
3,9.056245,197.666301,17403.532167,7.688917,337.460176,414.766631,15.349869,63.696746,3.319354,0
4,5.039374,142.860598,40829.353167,7.271543,NaN,386.803057,16.823773,52.297113,4.957420,0
...,...,...,...,...,...,...,...,...,...,...
2615,8.060610,208.042711,15489.325660,5.620299,361.970424,423.420838,15.371550,75.445589,3.600906,0
2616,8.238997,199.594539,25046.798640,9.288020,350.835986,328.363398,18.743231,54.416965,3.089924,1
2617,5.694694,240.712182,7998.674511,8.124265,NaN,477.047807,15.459307,68.895603,3.870611,1
2618,NaN,203.050244,28184.900527,7.076634,344.524179,445.700761,19.775367,53.270152,4.456104,0
2619,5.907078,213.471081,41839.456449,7.924762,312.329947,357.258970,15.598965,54.421879,4.296480,0

##### 93. ph값은 상당히 많은 결측치를 포함한다. 결측치를 제외한 나머지 데이터들 중 사분위값 기준 하위 25%의 값들의 평균값은?

# 의료 비용 예측 데이터
데이터 출처 :https://www.kaggle.com/mirichoi0218/insurance/code(참고, 데이터 수정)  
데이터 설명 : 의료비용 예측문제  
Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/MedicalCost/train.csv

In [124]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/MedicalCost/train.csv")
df

      age     sex     bmi  children smoker     region      charges
0      64  female  39.330         0     no  northeast  14901.51670
1      47  female  27.830         0    yes  southeast  23065.42070
2      52  female  33.300         2     no  southwest  10806.83900
3      33  female  22.135         1     no  northeast   5354.07465
4      30    male  31.400         1     no  southwest   3659.34600
...   ...     ...     ...       ...    ...        ...          ...
1065   39    male  24.510         2     no  northwest   6710.19190
1066   37    male  24.320         2     no  northwest   6198.75180
1067   18  female  26.315         0     no  northeast   2198.18985
1068   50    male  37.070         1     no  southeast   9048.02730
1069   49    male  31.350         1     no  northeast   9290.13950

[1070 rows x 7 columns]

##### 94. 흡연자와 비흡연자 각각 charges의 상위 10% 그룹의 평균의 차이는?

# 킹카운티 주거지 가격예측문제 데이터
데이터 출처 :https://www.kaggle.com/harlfoxem/housesalesprediction (참고, 데이터 수정)  
데이터 설명 : 킹카운티 주거지 가격 예측문제  
Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/kingcountyprice/train.csv

In [126]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/kingcountyprice//train.csv")
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,8961990160,20150413T000000,567500.0,3,2.50,2080,4556,2.0,0,0,...,8,2080,0,1999,0,98074,47.6036,-122.014,1530,5606
1,9455200205,20140604T000000,525000.0,3,2.00,1540,7800,1.0,0,0,...,8,1540,0,2004,0,98125,47.7041,-122.288,1510,7800
2,7853220670,20140918T000000,540000.0,3,2.50,2860,8935,2.0,0,0,...,8,2860,0,2004,0,98065,47.5336,-121.855,2650,6167
3,3298201170,20141110T000000,350000.0,3,1.00,940,7811,1.0,0,0,...,6,940,0,1959,0,98008,47.6195,-122.118,1180,7490
4,7972604355,20140521T000000,218000.0,3,1.00,1020,7874,1.0,0,0,...,7,1020,0,1956,0,98106,47.5175,-122.346,1290,7320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17285,9264930970,20150311T000000,345000.0,4,2.75,2200,13498,2.0,0,0,...,8,2200,0,1987,0,98023,47.3148,-122.350,2190,11850
17286,4206901215,20140612T000000,920000.0,4,3.25,2420,4000,1.5,0,0,...,9,1870,550,1911,0,98105,47.6567,-122.325,1810,4000
17287,3793500550,20140808T000000,289950.0,3,2.50,1670,6186,2.0,0,0,...,7,1670,0,2002,0,98038,47.3668,-122.031,2390,6924
17288,7787920080,20140616T000000,492500.0,5,2.50,2570,9962,2.0,0,0,...,8,2570,0,2006,0,98019,47.7275,-121.957,2890,9075
17289,321030010,20141015T000000,310000.0,4,2.50,2310,7384,2.0,0,0,...,8,2310,0,2010,0,98042,47.3737,-122.165,2310,7800

##### 95. bedrooms 의 빈도가 가장 높은 값을 가지는 데이터들의 price의 상위 10%와 하위 10%값의 차이를 구하여라

# 대학원 입학가능성 데이터
데이터 출처 :https://www.kaggle.com/mohansacharya/graduate-admissions(참고, 데이터 수정)  
데이터 설명 : 대학원 입학 가능성 예측  
Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/admission/train.csv

In [128]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/admission/train.csv")
df

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,246,328,110,4,4.0,2.5,9.02,1,0.81
1,100,323,113,3,4.0,4.0,8.88,1,0.79
2,79,296,95,2,3.0,2.0,7.54,1,0.44
3,53,334,116,4,4.0,3.0,8.00,1,0.78
4,444,321,114,5,4.5,4.5,9.16,1,0.87
...,...,...,...,...,...,...,...,...,...
395,47,329,114,5,4.0,5.0,9.30,1,0.86
396,14,307,109,3,4.0,3.0,8.00,1,0.62
397,28,298,98,2,1.5,2.5,7.50,1,0.44
398,149,339,116,4,4.0,3.5,9.80,1,0.96
399,470,326,114,4,4.0,3.5,9.16,1,0.86

##### 96. Serial No. 컬럼을 제외하고 ‘Chance of Admit’을 종속변수, 나머지 변수를 독립변수라 할때, 랜덤포레스트를 통해 회귀 예측을 할 떄 변수중요도 값을 출력하라 (시드값에 따라 순서는 달라질수 있음)

In [129]:
from sklearn.ensemble import RandomForestRegressor

df_t = df.drop([df.columns[0]],axis=1)
x = df_t.drop([df.columns[-1]],axis=1)
y = df_t[df.columns[-1]]

ml = RandomForestRegressor()

ml.fit(x,y)

result = pd.DataFrame({"importance" : ml.feature_importances_}, x.columns).sort_values("importance", ascending = False)
display(result)

                   importance
CGPA                 0.796762
GRE Score            0.104912
TOEFL Score          0.028279
SOP                  0.026277
LOR                  0.023452
University Rating    0.012868
Research             0.007450

# 레드 와인 퀄리티 예측 데이터
데이터 출처 :https://www.kaggle.com/uciml/red-wine-quality-cortez-et-al-2009(참고, 데이터 수정)  
데이터 설명 : 레드 와인 퀄리티 예측문제  
Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/redwine/train.csv

In [130]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/redwine/train.csv")
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,5.0,0.38,0.01,1.6,0.048,26.0,60.0,0.99084,3.70,0.75,14.0,6
1,5.0,0.42,0.24,2.0,0.060,19.0,50.0,0.99170,3.72,0.74,14.0,8
2,7.1,0.36,0.30,1.6,0.080,35.0,70.0,0.99693,3.44,0.50,9.4,5
3,7.6,0.29,0.49,2.7,0.092,25.0,60.0,0.99710,3.31,0.61,10.1,6
4,7.7,0.51,0.28,2.1,0.087,23.0,54.0,0.99800,3.42,0.74,9.2,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1274,8.8,0.61,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,5
1275,8.0,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.5,7
1276,10.0,0.35,0.45,2.5,0.092,20.0,88.0,0.99918,3.15,0.43,9.4,5
1277,8.0,1.18,0.21,1.9,0.083,14.0,41.0,0.99532,3.34,0.47,10.5,5
1278,8.6,0.47,0.30,3.0,0.076,30.0,135.0,0.99760,3.30,0.53,9.4,5

##### 97. quality 값이 3인 그룹과 8인 데이터그룹의 각 컬럼별 독립변수의 표준편차 값의 차이를 구할때 그값이 가장 큰 컬럼명을 구하여라

In [131]:
abs(df[df["quality"] == 8].std() - df[df["quality"] == 3].std()).sort_values(ascending = False).index[0]

'total sulfur dioxide'

# 약물 분류 데이터
데이터 출처 :https://www.kaggle.com/prathamtripathi/drug-classification(참고, 데이터 수정)  
데이터 설명 : 투약하는 약을 분류  
Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/drug/train.csv

In [132]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/drug/train.csv")
df

     Age Sex      BP Cholesterol  Na_to_K  Drug
0     20   F  NORMAL      NORMAL    9.281     4
1     24   M    HIGH      NORMAL    9.475     1
2     34   M  NORMAL        HIGH   22.456     0
3     17   M  NORMAL      NORMAL   10.832     4
4     72   M     LOW        HIGH   16.310     0
..   ...  ..     ...         ...      ...   ...
152   58   F     LOW        HIGH   26.645     0
153   30   F  NORMAL        HIGH   10.443     4
154   20   F     LOW      NORMAL   11.686     4
155   58   M    HIGH        HIGH   18.991     0
156   16   M     LOW        HIGH   12.006     3

[157 rows x 6 columns]

##### 98. 남성들의 연령대별 (10살씩 구분 0~9세 10~19세 …) Na_to_K값의 평균값을 구해서 데이터 프레임으로 표현하여라

In [133]:
def age(x):
    return x // 10 * 10

target = df[df["Sex"] == "M"]
target["Age_Group"] = target["Age"].apply(age)
target[["Na_to_K", "Age_Group"]].groupby("Age_Group").mean()

C:\Users\cho03\AppData\Local\Temp\ipykernel_30160\1264550460.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  target["Age_Group"] = target["Age"].apply(age)

             Na_to_K
Age_Group
10         13.627000
20         18.260769
30         15.244143
40         13.897273
50         14.811273
60         14.284308
70         11.363857

# 사기회사 분류 데이터
데이터 출처 :https://www.kaggle.com/sid321axn/audit-data(참고, 데이터 수정)  
데이터 설명 : 사기회사 분류  
Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/audit/train.csv

In [134]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/audit/train.csv")
df

,Sector_score,LOCATION_ID,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,2.72,14,4.53,0.6,2.718,87.93,0.6,52.758,92.46,5.0,...,0.4,0,0.2,0.0,4.0,108.362,0.4,0.5,21.6724,1
1,3.41,16,12.68,0.6,7.608,41.00,0.6,24.600,53.68,5.5,...,0.4,0,0.2,0.0,4.4,41.936,0.4,0.5,8.3872,1
2,2.72,11,3.11,0.6,1.866,113.97,0.6,68.382,117.08,5.5,...,0.4,0,0.2,0.0,4.4,88.832,0.4,0.5,17.7664,1
3,3.41,8,1.12,0.4,0.448,0.00,0.2,0.000,1.12,5.0,...,0.4,0,0.2,0.0,2.2,1.848,0.4,0.5,0.3696,0
4,55.57,9,1.06,0.4,0.424,0.00,0.2,0.000,1.06,5.0,...,0.4,0,0.2,0.0,2.2,1.824,0.4,0.5,0.3648,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,1.85,19,4.04,0.6,2.424,0.00,0.2,0.000,4.04,5.0,...,1.2,0,0.2,0.0,2.8,4.782,1.2,0.5,2.8692,1
616,3.89,37,4.18,0.6,2.508,4.83,0.2,0.966,9.01,5.5,...,0.4,0,0.2,0.0,3.2,14.492,0.4,0.5,2.8984,1
617,3.89,15,1.00,0.4,0.400,0.00,0.2,0.000,1.00,5.0,...,0.4,0,0.2,0.0,2.2,1.872,0.4,0.5,0.3744,0
618,55.57,6,2.24,0.6,1.344,7.26,0.6,4.356,9.50,5.0,...,0.4,0,0.2,0.0,3.6,7.148,0.4,0.5,1.4296,1
619,55.57,8,2.41,0.6,1.446,4.69,0.6,2.814,7.10,5.0,...,0.4,0,0.2,0.0,3.6,5.710,0.4,0.5,1.1420,1

##### 99. 데이터의 Risk 값에 따른 score_a와 score_b의 평균값을 구하여라

In [135]:
df[["Score_A", "Score_B", "Risk"]].groupby("Risk").mean()

       Score_A   Score_B
Risk
0     0.262234  0.225532
1     0.490164  0.444262

# 센서데이터 동작유형 분류 데이터
데이터 출처 :https://www.kaggle.com/kyr7plus/emg-4(참고, 데이터 수정)  
데이터 설명 : 센서데이터로 동작 유형 분류  
Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/train.csv

In [136]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/train.csv")
df

,motion_0,motion_1,motion_2,motion_3,motion_4,motion_5,motion_6,motion_7,motion_8,motion_9,...,motion_55,motion_56,motion_57,motion_58,motion_59,motion_60,motion_61,motion_62,motion_63,pose
0,-6.0,8.0,5.0,6.0,-12.0,-27.0,5.0,24.0,-8.0,-5.0,...,-1.0,-3.0,-6.0,-9.0,-7.0,36.0,68.0,3.0,-3.0,1
1,-32.0,-3.0,-4.0,-5.0,-1.0,16.0,0.0,-5.0,42.0,2.0,...,-17.0,-12.0,-1.0,-1.0,0.0,-26.0,-11.0,-4.0,-9.0,1
2,35.0,-2.0,-1.0,1.0,-25.0,-16.0,-3.0,-20.0,10.0,1.0,...,6.0,-65.0,6.0,-10.0,-31.0,-19.0,-3.0,-47.0,-17.0,0
3,-15.0,-6.0,-3.0,-5.0,27.0,37.0,-2.0,-2.0,19.0,5.0,...,2.0,11.0,0.0,-2.0,-4.0,-7.0,15.0,3.0,14.0,1
4,60.0,3.0,0.0,-7.0,-6.0,-10.0,-6.0,7.0,-11.0,-4.0,...,-12.0,17.0,-3.0,1.0,2.0,-2.0,20.0,18.0,10.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4645,40.0,-8.0,-14.0,-27.0,10.0,12.0,-35.0,12.0,-21.0,1.0,...,84.0,-1.0,2.0,-1.0,-1.0,-9.0,-21.0,-95.0,-90.0,0
4646,-35.0,-4.0,-6.0,0.0,-4.0,-11.0,-24.0,-27.0,46.0,12.0,...,-2.0,-2.0,-1.0,-3.0,2.0,5.0,36.0,51.0,6.0,0
4647,-34.0,-17.0,-4.0,10.0,14.0,-22.0,-6.0,-24.0,-17.0,26.0,...,-8.0,-23.0,-26.0,-6.0,-4.0,10.0,-13.0,-33.0,-14.0,0
4648,21.0,3.0,0.0,-15.0,5.0,2.0,48.0,22.0,-22.0,2.0,...,-7.0,-2.0,3.0,-4.0,-25.0,12.0,0.0,10.0,-33.0,0
4649,3.0,31.0,0.0,-6.0,-16.0,2.0,-38.0,-35.0,-19.0,-17.0,...,9.0,-3.0,-10.0,-9.0,14.0,-1.0,-1.0,-31.0,-18.0,0

##### 100. pose값에 따른 각 motion컬럼의 중간값의 가장 큰 차이를 보이는 motion컬럼은 어디이며 그값은?

In [137]:
t = df.groupby("pose").median().T
t

pose         0    1
motion_0  -2.0 -2.0
motion_1  -1.0 -1.0
motion_2  -1.0 -1.0
motion_3   0.0 -1.0
motion_4   0.0  0.0
...        ...  ...
motion_59  0.0 -1.0
motion_60 -1.0  1.0
motion_61 -1.0  1.0
motion_62 -5.0 -1.0
motion_63 -1.0 -1.0

[64 rows x 2 columns]

In [138]:
dfs = abs(t[0] - t[1]).sort_values().reset_index()
dfs[dfs[0] == dfs[0].max()]["index"].values

array(['motion_54', 'motion_62'], dtype=object)

# 현대 차량 가격 분류문제 데이터
데이터 출처 :https://www.kaggle.com/mysarahmadbhat/hyundai-used-car-listing(참고, 데이터 수정)  
데이터 설명 : 현대 차량가격 분류문제  
Data url :hhttps://raw.githubusercontent.com/Datamanim/datarepo/main/hyundai/train.csv

In [139]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/hyundai/train.csv")
df

,model,year,price,transmission,mileage,fuelType,tax(£),mpg,engineSize
0,Tucson,2016,12795,Manual,36263,Diesel,30,61.7,1.7
1,I10,2012,3995,Manual,22089,Petrol,20,61.4,1.2
2,I30,2019,24000,Manual,555,Petrol,145,34.0,2.0
3,Tucson,2017,12995,Manual,32147,Diesel,30,61.7,1.7
4,Tucson,2018,14991,Semi-Auto,32217,Diesel,150,57.6,1.7
...,...,...,...,...,...,...,...,...,...
3883,I10,2016,6500,Manual,16309,Petrol,30,57.6,1.2
3884,Tucson,2018,15999,Semi-Auto,7723,Diesel,145,57.6,1.7
3885,I30,2016,8990,Manual,33466,Diesel,0,78.4,1.6
3886,Ioniq,2019,18990,Automatic,11816,Hybrid,135,78.5,1.6
3887,I10,2017,7998,Manual,19625,Petrol,145,57.7,1.2

##### 101. 정보(row수)가 가장 많은 상위 3차종의 price값의 각 평균값은?

In [140]:
df[df["model"].isin(df.value_counts("model").index[:3])].groupby("model")["price"].mean().to_frame()

               price
model
I10      7646.137891
I30     11651.821759
Tucson  15805.441373

# 당뇨여부판단 데이터
데이터 출처 :https://www.kaggle.com/pritsheta/diabetes-dataset(참고, 데이터 수정)  
데이터 설명 : 당뇨여부 판단하기  
Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/diabetes/train.csv

In [141]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/diabetes/train.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,3,102,74,0,0,29.5,0.121,32,0
1,2,144,58,33,135,31.6,0.422,25,1
2,5,136,82,0,0,0.0,0.640,69,0
3,13,145,82,19,110,22.2,0.245,57,0
4,1,117,60,23,106,33.8,0.466,27,0
...,...,...,...,...,...,...,...,...,...
609,3,187,70,22,200,36.4,0.408,36,1
610,11,138,74,26,144,36.1,0.557,50,1
611,5,168,64,0,0,32.9,0.135,41,1
612,1,79,60,42,48,43.5,0.678,23,0
613,1,140,74,26,180,24.1,0.828,23,0

##### 102. Outcome 값에 따른 각 그룹의 각 컬럼의 평균 차이를 구하여라

In [142]:
abs(df[df["Outcome"] == 0].mean() - df[df["Outcome"] == 1].mean())

Pregnancies                  1.574159
Glucose                     29.943995
BloodPressure                3.202079
SkinThickness                2.952033
Insulin                     33.398645
BMI                          4.541437
DiabetesPedigreeFunction     0.143646
Age                          5.866939
Outcome                      1.000000
dtype: float64

# 넷플릭스 주식 데이터
데이터 출처 :https://www.kaggle.com/pritsheta/netflix-stock-data-from-2002-to-2021(참고, 데이터 수정)  
데이터 설명 : 넷플릭스 주식데이터  
Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/nflx/NFLX.csv

In [143]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/nflx/NFLX.csv")
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2002-05-23,1.156429,1.242857,1.145714,1.196429,1.196429,104790000
1,2002-05-24,1.214286,1.225000,1.197143,1.210000,1.210000,11104800
2,2002-05-28,1.213571,1.232143,1.157143,1.157143,1.157143,6609400
3,2002-05-29,1.164286,1.164286,1.085714,1.103571,1.103571,6757800
4,2002-05-30,1.107857,1.107857,1.071429,1.071429,1.071429,10154200
...,...,...,...,...,...,...,...
4869,2021-09-24,592.500000,592.979980,583.640015,592.390015,592.390015,2124800
4870,2021-09-27,587.950012,593.580017,576.929993,592.640015,592.640015,2504700
4871,2021-09-28,589.000000,599.539978,580.159973,583.849976,583.849976,4431100
4872,2021-09-29,589.010010,609.880005,588.010010,599.059998,599.059998,6221000
4873,2021-09-30,608.049988,619.000000,608.049988,610.340027,610.340027,6612600

##### 103. 매년 5월달의 open가격의 평균값을 데이터 프레임으로 표현하라

In [144]:
df["Date"] = pd.to_datetime(df["Date"])
df[df["Date"].dt.month == 5].groupby(df["Date"].dt.year)["Open"].mean().to_frame()

            Open
Date
2002    1.155833
2003    1.641497
2004    4.261143
2005    1.951905
2006    4.163571
2007    3.159351
2008    4.435034
2009    5.790571
2010   14.417071
2011   34.650272
2012   10.523247
2013   31.936429
2014   51.121292
2015   85.057429
2016   92.705715
2017  158.255455
2018  329.779541
2019  359.664548
2020  433.880499
2021  496.923996

# nba 선수 능력치 데이터
데이터 출처 :https://www.kaggle.com/datasets/vivovinco/nba-player-stats(참고, 데이터 수정)  
Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/nba/nba.csv

In [145]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/nba/nba.csv", encoding = "latin", sep = ";")
df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Precious Achiuwa,C,22,TOR,73,28,23.6,3.6,8.3,...,0.595,2.0,4.5,6.5,1.1,0.5,0.6,1.2,2.1,9.1
1,2,Steven Adams,C,28,MEM,76,75,26.3,2.8,5.1,...,0.543,4.6,5.4,10.0,3.4,0.9,0.8,1.5,2.0,6.9
2,3,Bam Adebayo,C,24,MIA,56,56,32.6,7.3,13.0,...,0.753,2.4,7.6,10.1,3.4,1.4,0.8,2.6,3.1,19.1
3,4,Santi Aldama,PF,21,MEM,32,0,11.3,1.7,4.1,...,0.625,1.0,1.7,2.7,0.7,0.2,0.3,0.5,1.1,4.1
4,5,LaMarcus Aldridge,C,36,BRK,47,12,22.3,5.4,9.7,...,0.873,1.6,3.9,5.5,0.9,0.3,1.0,0.9,1.7,12.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807,601,Thaddeus Young,PF,33,TOR,26,0,18.3,2.6,5.5,...,0.481,1.5,2.9,4.4,1.7,1.2,0.4,0.8,1.7,6.3
808,602,Trae Young,PG,23,ATL,76,76,34.9,9.4,20.3,...,0.904,0.7,3.1,3.7,9.7,0.9,0.1,4.0,1.7,28.4
809,603,Omer Yurtseven,C,23,MIA,56,12,12.6,2.3,4.4,...,0.623,1.5,3.7,5.3,0.9,0.3,0.4,0.7,1.5,5.3
810,604,Cody Zeller,C,29,POR,27,0,13.1,1.9,3.3,...,0.776,1.9,2.8,4.6,0.8,0.3,0.2,0.7,2.1,5.2
811,605,Ivica Zubac,C,24,LAC,76,76,24.4,4.1,6.5,...,0.727,2.9,5.6,8.5,1.6,0.5,1.0,1.5,2.7,10.3

##### 104. Tm 컬럼은 각 팀의 이름을 의미한다. TOR팀의 평균나이를 소수 4째 자리까지 구하여라

In [146]:
round(df[df["Tm"] == "TOR"]["Age"].mean(), 4)

np.float64(24.8696)

##### 105. Pos 컬럼은 포지션을 의미한다. 전체 선수 중 최소나이대의 선수들을 필터하고 그들 중 가장 많은 포지션은 무엇인지 확인하라

In [147]:
df[df["Age"] == df["Age"].min()]["Pos"].value_counts().index[0]

'SG'

##### 106. 선수들의 이름은 first_name+ 공백 + last_name으로 이루어져 있다. 가장 많은 first_name은 무엇이며 몇 회 발생하는지 확인하라

In [148]:
df["Player"].str.split().str[0].str.lower().value_counts().head(1)

Player
justin    14
Name: count, dtype: int64

##### 107. PTS컬럼은 경기당 평균득점수 이다. 각포지션별로 경기당 평균득점수의 평균을 구하여라

In [149]:
df.groupby("Pos")["PTS"].mean().sort_values()

Pos
SF        7.270253
SG-SF     7.360000
C         7.690769
PF        7.737500
SG        7.810553
PG        8.325161
PF-SF     8.500000
SF-SG     8.660000
SG-PG     9.525000
C-PF     12.850000
PG-SG    22.000000
Name: PTS, dtype: float64

##### 108. G컬럼은 참여한 경기의 숫자이다. 각 팀별로 가장 높은 경기참여 수를 가진 선수들의 경기 참여 숫자의 평균을 구하여라

In [150]:
df.sort_values(["Tm", "G"]).groupby("Tm").tail(1)["G"].mean()

np.float64(77.51612903225806)

##### 109. Tm의 값이 MIA이며 Pos는 C또는 PF인 선수의 MP값의 평균은?

In [151]:
df[(df["Tm"] == "MIA") & (df["Pos"].isin(["C", "PF"]))]["MP"].mean()

np.float64(16.7875)

##### 110. 전체 데이터중 G의 평균값의 1.5배 이상인 데이터들만 추출했을때 3P값의 평균은?

In [152]:
df[df["G"] >= 1.5 * df["G"].mean()]["3P"].mean()

np.float64(1.3853658536585365)

##### 111. Age의 평균 이상인 그룹과 평균 미만인 그룹간의 G값의 평균의 차이는?

In [153]:
df[df["Age"] >= df["Age"].mean()]["G"].mean() - df[df["Age"] < df["Age"].mean()]["G"].mean()

np.float64(3.787674551781862)

##### 112. 평균나이가 가장 젊은 팀은 어디인가?

In [154]:
df.groupby("Tm")["Age"].mean().sort_values().index[0]

'MEM'

##### 113. Pos그룹별 평균 MP값을 구하여라

In [155]:
df.groupby("Pos")["MP"].mean()

Pos
C        16.990000
C-PF     25.350000
PF       17.937500
PF-SF    27.300000
PG       19.547742
PG-SG    37.200000
SF       17.514557
SF-SG    20.340000
SG       18.554271
SG-PG    22.950000
SG-SF    19.620000
Name: MP, dtype: float64