#### 문제: 다음은 22명의 학생들이 국어시험에서 받은 점수이다. 학생들의 평균이 75보다 크다고 할 수 있는가?
귀무가설(H0): 모평균은 mu와 같다. (μ = mu), 학생들의 평균은 75이다  
대립가설(H1): 모평균은 mu보다 크다. (μ > mu), 학생들의 평균은 75보다 크다

In [1]:
# 검정통계량, p-value, 검정결과를 출력하시오

# 데이터
scores = [75, 80, 68, 72, 77, 82, 81, 79, 70, 74, 76, 78, 81, 73, 81, 78, 75, 72, 74, 79, 78, 79]

from scipy import stats
mu = 75
alpha = 0.05

statistic, p_value = stats.ttest_1samp(scores, mu, alternative = "greater")
print("검정통계량 :", statistic)
print("p-value :", p_value)

if p_value < alpha: print("H0 기각")
else: print("H1 채택")

검정통계량 : 1.765879233231226
p-value : 0.04597614747709146
H0 기각

#### 어떤 특정 약물을 복용한 사람들의 평균 체온이 복용하지 않은 사람들의 평균 체온과 유의미하게 다른지 검정해보려고 합니다.

가정: 
- 약물을 복용한 그룹과 복용하지 않은 그룹의 체온 데이터가 각각 주어져 있다고 가정합니다.
- 각 그룹의 체온은 정규분포를 따른다고 가정합니다.

In [2]:
# 가설 설정
# H0: 약물을 복용한 그룹과 복용하지 않은 그룹의 평균 체온은 유의미한 차이가 없다.
# H1: 약물을 복용한 그룹과 복용하지 않은 그룹의 평균 체온은 유의미한 차이가 있다.

# 데이터 수집
group1 = [36.8, 36.7, 37.1, 36.9, 37.2, 36.8, 36.9, 37.1, 36.7, 37.1]
group2 = [36.5, 36.6, 36.3, 36.6, 36.9, 36.7, 36.7, 36.8, 36.5, 36.7]
alpha = 0.05

statistic, p_value = stats.ttest_ind(group1, group2)
print("검정통계량 :", statistic)
print("p-value :", p_value)

if p_value < alpha: print("H0 기각")
else: print("H1 채택")

검정통계량 : 3.7964208654863336
p-value : 0.001321891476703691
H0 기각

#### 주어진 데이터는 고혈압 환자 치료 전후의 혈압이다. 해당 치료가 효과가 있는지 대응(쌍체)표본 t-검정을 진행하시오
- 귀무가설(H0): μ >= 0
- 대립가설(H1): μ < 0
- μ = (치료 후 혈압 - 치료 전 혈압)의 평균
- 유의수준: 0.05
  
1. μ 의 표본평균은?(소수 둘째자리까지 반올림)
2. 검정통계량 값은?(소수 넷째자리까지 반올림)
3. p-값은?(소수 넷째자리까지 반올림)
4. 가설검정의 결과는? (유의수준 5%)

In [3]:
import pandas as pd
df = pd.read_csv("../data/high_blood_pressure.csv")
df.head()

     Id     sex  age  bp_pre  bp_post
0  p001    Male   33     149      129
1  p002    Male   39     168      168
2  p003    Male   70     176      155
3  p004  Female   41     169      178
4  p005    Male   48     160      126

In [4]:
# 1
print("1. mu :", round((df["bp_post"] - df["bp_pre"]).mean(), 2))


# 2, 3, 4
statistic, p_value = stats.ttest_rel(df["bp_post"], df["bp_pre"], alternative = "less")
alpha = 0.05

print("2. 검정통계량 :", round(statistic, 4))
print("3. p-value :", round(p_value, 4))

if p_value < alpha: print("4. H0 기각")
else: print("4. H1 채택")

1. mu : -6.12
2. 검정통계량 : -3.0002
3. p-value : 0.0016
4. H0 기각

#### 세 가지 다른 교육 방법(A, B, C)을 사용하여 수험생들의 시험 성적을 개선시키는 효과를 평가하고자 한다. 30명의 학생들을 무작위로 세 그룹으로 배정하여 교육을 실시하였고, 시험을 보고 성적을 측정하였습니다. 다음은 각 그룹의 학생들의 성적 데이터입니다.
- 귀무가설(H0): 세 그룹(A, B, C) 간의 평균 성적 차이가 없다.
- 대립가설(H1 또는 Ha): 세 그룹(A, B, C) 간의 평균 성적 차이가 있다.

1. 다음 주어진 데이터로 일원배치법을 수행하여 그룹 간의 평균 성적 차이가 있는지 검정하세요
- f값 (소수 둘째자리)
- p값 (소수 여섯째자리)
- 검정결과 출력

In [5]:
# 각 그룹의 데이터
groupA = [85, 92, 78, 88, 83, 90, 76, 84, 92, 87]
groupB = [79, 69, 84, 78, 79, 83, 79, 81, 86, 88]
groupC = [75, 68, 74, 65, 77, 72, 70, 73, 78, 75]

In [6]:
# 1.
f_value, p_value = stats.f_oneway(groupA, groupB, groupC)
print("f-value :", round(f_value, 2))
print("p-value :", round(p_value, 6))
if p_value < 0.05 : print("H0 기각")
else : print("H0 채택")

f-value : 16.88
p-value : 1.8e-05
H0 기각

#### 12명의 수험생이 빅데이터 분석기사 시험에서 받은 점수이다. Shapiro-Wilk 검정을 사용하여 데이터가 정규 분포를 따르는지 검증하시오
- 귀무 가설(H0): 데이터는 정규 분포를 따른다.
- 대립 가설(H1): 데이터는 정규 분포를 따르지 않는다.
- Shapiro-Wilk 검정 통계량, p-value, 검증결과를 출력하시오

In [7]:
data = [75, 83, 81, 92, 68, 77, 78, 80, 85, 95, 79, 89]

from scipy import stats
statistic, p_value = stats.shapiro(data)

print("검정통계량 :", statistic)
print("p-value :", p_value)
if p_value < 0.05 : print("H0 기각")
else : print("H0 채택")

검정통계량 : 0.9768091723993144
p-value : 0.9676506711851194
H0 채택

#### iris에서 Sepal Length와 Sepal Width의 상관계수 계산하고 소수 둘째자리까지 출력하시오

In [8]:
import pandas as pd
from sklearn.datasets import load_iris

# iris 데이터셋 로드
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [9]:
print(round(df.corr()["sepal length (cm)"]["sepal width (cm)"], 2))

-0.12

### 로지스틱 회귀

#### Pclass, Gender, sibsp, parch를 독립변수로 사용하여 Survived 로지스틱 회귀모형을 실시하였을 때, parch변수의 계수값은? 단, Pclass는 범주형 변수이다¶

In [10]:
df = pd.read_csv("../data/Titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [11]:
import statsmodels.formula.api as smf
model = smf.logit("Survived ~ C(Pclass) + C(Gender) + SibSp + Parch", data = df).fit() # statsmodels에서는 문자열은 자동으로 범주형으로 인식 -> C(Gender) 안해도 됨, but Pclass는 범주형 -> C(Pclass) 안하면 연속형으로 인식
print(model.params["Parch"])

Optimization terminated successfully.
         Current function value: 0.459565
         Iterations 6
-0.0498472583421679

#### 문제: 두 교육 방법의 효과 비교
연구자는 두 가지 다른 교육 방법이 학생들의 성적에 미치는 영향을 비교하고자 합니다. 연구자는 무작위로 선발된 20명의 학생들을 두 그룹으로 나누어 한 그룹에는 교육 방법 A를, 다른 그룹에는 교육 방법 B를 적용합니다. 교육이 끝난 후, 두 그룹의 성적을 비교하기 위해 독립 표본 t-검정과 ANOVA F-검정을 실시하려고 합니다.
  
다음은 두 그룹의 성적입니다: 다음의 두 가지 검정을 사용하여 두 교육 방법 간의 성적 차이가 통계적으로 유의한지를 검증하세요

1. 독립 표본 t-검정을 실시하여 t 통계량을 구하세요.
2. 독립 표본 t-검정을 실시하여 p-값을 구하세요.
3. ANOVA F-검정을 실시하여 F 통계량을 구하세요.
4. ANOVA F-검정을 실시하여 p-값을 구하세요.

In [12]:
import pandas as pd
df = pd.DataFrame({
    'A':[77, 75, 82, 80, 81, 83, 84, 76, 75, 87],
    'B':[80, 74, 77, 79, 71, 74, 78, 69, 70, 72],
})

df_A = df["A"]
df_B = df["B"]

In [13]:
# 1, 2
statistic, p_value = stats.ttest_ind(df_A, df_B)
print("1. t 통계량 :", statistic)
print("2. p-value :", p_value)

statistic, p_value = stats.f_oneway(df_A, df_B)
print("3. f 통계량 :", statistic)
print("4. p-value :", p_value)

1. t 통계량 : 3.1068522301122954
2. p-value : 0.006087373605949963
3. f 통계량 : 9.652530779753763
4. p-value : 0.006087373605949924

#### 카이제곱 적합도 검정
고등학교에서는 졸업생들이 선택하는 대학 전공 분야의 선호도가 시간이 지남에 따라 변하지 않는다고 가정합니다. 학교 측은 최근 졸업생들의 전공 선택이 과거와 같은 패턴을 따르는지 알아보기 위해 적합도 검정을 실시하기로 결정했습니다.  

과거 자료에 따르면 졸업생들이 선택하는 전공의 분포는 다음과 같습니다:  

인문학: 20% 사회과학: 30% 자연과학: 25% 공학: 15% 기타: 10% 올해 졸업한 학생 200명의 전공 선택 분포는 다음과 같았습니다:  

인문학: 30명 사회과학: 60명 자연과학: 50명 공학: 40명 기타: 20명 이 데이터를 바탕으로, 졸업생들의 전공 선택 패턴이 과거와 유사한지를 알아보기 위해 카이제곱 적합도 검정을 실시해야 합니다. 유의 수준은 0.05로 설정합니다.  

1. 검정 통계량?
2. p-value?
3. 유의수준 하 귀무가설 기각 또는 채택?

In [14]:
real_data = [30, 60, 50, 40, 20]
expected_data = [200 * 0.2, 200 * 0.3, 200 * 0.25, 200 * 0.15, 200 * 0.1]

from scipy import stats
statistic, p_value = stats.chisquare(real_data, expected_data)

print("1. 검정통계량 :", statistic)
print("2. p-value :", p_value)
if p_value < 0.05 : print("3. H0 기각")
else: print("3. H0 채택")

1. 검정통계량 : 5.833333333333334
2. p-value : 0.21194558437271782
3. H0 채택

#### 지지도, 신뢰도, 향상도
1. '빼빼로'와 '딴짓초코'가 함께 팔린 거래의 지지도를 계산하세요.
2. '빼빼로'가 팔린 거래 중에서 '빼빼로'와 '오징어칩'이 함께 팔린 거래의 신뢰도를 계산하세요.
3. '빼빼로'와 '양조위빵'의 향상도를 계산하세요.

In [15]:
import pandas as pd

# 데이터
df = pd.DataFrame({
    'transaction': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    '빼빼로': [1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
    '딴짓초코': [0, 1, 1, 0, 1, 0, 1, 1, 0, 0],
    '양조위빵': [1, 0, 0, 1, 1, 1, 0, 0, 1, 0],
    '오징어칩': [0, 1, 1, 0, 0, 1, 0, 1, 1, 1],
    '초코파이': [1, 1, 0, 0, 1, 0, 1, 1, 0, 0]
})
df

   transaction  빼빼로  딴짓초코  양조위빵  오징어칩  초코파이
0            1    1     0     1     0     1
1            2    0     1     0     1     1
2            3    1     1     0     1     0
3            4    1     0     1     0     0
4            5    0     1     1     0     1
5            6    1     0     1     1     0
6            7    1     1     0     0     1
7            8    0     1     0     1     1
8            9    1     0     1     1     0
9           10    1     0     0     1     0

In [16]:
# 1. 지지도 = P(A ∩ B)
print("1. 지지도 :", len((df[(df["빼빼로"] == 1) & (df["딴짓초코"] == 1)])) / len(df))

# 2. 신뢰도 = P(A ∩ B) / P(A)
print("2. 신뢰도 :", len((df[(df["빼빼로"] == 1) & (df["오징어칩"] == 1)])) / len(df[df["빼빼로"] == 1]))

# 3. 향상도 = P(A ∩ B) / (P(A) * P(B))
print("3. 향상도 :", len((df[(df["빼빼로"] == 1) & (df["양조위빵"] == 1)])) / (((len(df[df["빼빼로"] == 1])) / len(df)) * ((len(df[df["양조위빵"] == 1])) / len(df))))

1. 지지도 : 0.2
2. 신뢰도 : 0.5714285714285714
3. 향상도 : 11.428571428571429

#### 포아송분포
문제: 한 서점에서는 평균적으로 하루에 3명의 고객이 특정 잡지를 구매합니다. 이 데이터는 포아송 분포를 따른다고 가정할 때, 다음 질문에 대한 답을 구하세요.  

1. 하루에 정확히 5명의 고객이 잡지를 구매할 확률은 얼마입니까? (%로 값을 정수로 입력하시오)  
2. 하루에 적어도 2명의 고객이 잡지를 구매할 확률은 얼마입니까? (%로 값을 정수로 입력하시오)  
포아송 분포의 확률 질량 함수(PMF) : $P(X = k) = \frac{e^{-λ}λ^k}{k!}$

λ는 단위 시간(또는 단위 공간)당 평균 발생 횟수이고, k는 특정 시간(또는 공간) 동안의 이벤트 발생 횟수입니다.

In [17]:
from scipy import stats
print("1. 하루에 정확히 5명의 고객이 잡지를 구매할 확률 :", stats.poisson.pmf(5, 3))
print("2. 하루에 적어도 2명의 고객이 잡지를 구매할 확률 :", 1 - stats.poisson.cdf(1, 3))

1. 하루에 정확히 5명의 고객이 잡지를 구매할 확률 : 0.10081881344492458
2. 하루에 적어도 2명의 고객이 잡지를 구매할 확률 : 0.8008517265285442

#### 성별과 시험합격은 독립적인가를 검정하시오!
1. 검정 통계량?
2. p-value?
3. 귀무가설 기준 (기각/채택)?
4. 남자의 합격 기대 빈도?

In [18]:
import pandas as pd
from scipy import stats

# 데이터 프레임 생성
df = pd.DataFrame({'남자': [100, 200],
                   '여자': [130, 170]},
                  index=['합격', '불합격'])

# 데이터 프레임 출력
df

      남자   여자
합격   100  130
불합격  200  170

In [19]:
statistic, p_value, dof, expected_freq = stats.chi2_contingency(df)

print("1. 검정통계량 :", statistic)
print("2. p-value :", p_value)
if p_value < 0.05: print("3. H0 기각")
else: print("3. H0 채택")

print("4. 남자의 합격 기대 빈호 :", expected_freq[0][0])

1. 검정통계량 : 5.929494712103407
2. p-value : 0.01488951060599475
3. H0 기각
4. 남자의 합격 기대 빈호 : 115.0

#### 베르누이 분포와 이항분포
[베르누이 분포] 다음 데이터는 100번의 시도에서 각각 성공(1) 또는 실패(0)를 나타냅니다. 이 데이터를 바탕으로 각 시도의 성공 확률을 계산하시오.  
[이항분포] 1번 문제에서 계산한 성공 확률을 사용하여, 100번의 시도 중 정확히 60번 성공할 확률을 계산하시오.

In [20]:
import pandas as pd

df = pd.read_csv("../data/t3_success.csv")
df.head()

   Success
0        1
1        0
2        0
3        1
4        1

In [21]:
p = df[df["Success"] == 1].sum() / len(df)
print("100번의 시도 중 60번 성공할 확률 :", stats.binom.pmf(60, 100, p))

100번의 시도 중 60번 성공할 확률 : [0.07464986]

#### ❌ 점 추정과 구간 추정
데이터셋은 어떤 도시의 일일 평균 온도 입니다.  
  
점추정: 데이터셋을 기반으로 이 도시의 평균 연간 온도를 점추정하세요. (반올림하여 소수 둘째자리까지)  
구간추정: 95% 신뢰수준에서 이 도시의 평균 연간 온도에 대한 신뢰구간을 구하세요. (반올림하여 소수 둘째자리까지)

In [22]:
df = pd.read_csv("../data/daily_temperatures.csv")
df.head()

   Daily Average Temperature
0                  28.820262
1                  22.000786
2                  24.893690
3                  31.204466
4                  29.337790

In [23]:
# 점추정: 샘플 평균 계산
sample_mean = df["Daily Average Temperature"].mean()
print("점 추정 : ", round(sample_mean, 2))

# 구간추정: 샘플 표준편차 계산 및 신뢰구간 계산
confidence_level = 0.95
sample_std = df["Daily Average Temperature"].std()

# 자유도 n - 1로 설정
n_samples = len(df)

# 95% 신뢰구간 계산
CI = stats.t.interval(confidence_level, df = n_samples - 1, loc = sample_mean, scale = sample_std / (n_samples**0.5))
print("구간 추정 : ", CI)

점 추정 :  19.94
구간 추정 :  (np.float64(19.427887094620406), np.float64(20.44726799333667))

In [24]:
import numpy as np

sample_mean = df["Daily Average Temperature"].mean()
sample_std = df["Daily Average Temperature"].std()
n = len(df)

# t 임계값 (자유도 n-1, 양측 95%)
t_critical = stats.t.ppf(0.975, df=n-1)

margin = t_critical * (sample_std / np.sqrt(n))

lower = sample_mean - margin
upper = sample_mean + margin

print(f"신뢰구간: ({round(lower, 2)}, {round(upper, 2)})")

신뢰구간: (19.43, 20.45)

#### ❌ 크리스마스 장식 종류와 지역에 따라 판매량에 유의미한 차이가 있는지 이원 분산 분석을 통해 검정하세요¶
크리스마스 장식 종류(트리, 조명, 장식품)가 판매량에 미치는 영향을 분석하세요. 이때, 장식 종류의 F-value, p-value를 구하시오  
지역(북부, 남부, 동부, 서부)이 판매량에 미치는 영향을 분석하세요. 이때, 장식 종류의 F-value, p-value를 구하시오  
크리스마스 장식 종류와 지역의 상호작용이 판매량에 미치는 영향을 분석하세요. 이때, 장식 종류의 F-value, p-value를 구하시오

In [25]:
import pandas as pd
df = pd.read_csv("../data/christmas_decoration_sales.csv")

df.head()

  Decoration_Type Region  Sales
0              트리     북부     64
1              트리     남부     67
2              트리     동부     84
3              트리     서부     87
4              트리     북부     87

In [26]:
# 이원 분산 분석
import statsmodels.formula.api as smf
import statsmodels.api as sm

model = smf.ols("Sales ~ Decoration_Type * Region", data = df).fit()
sm.stats.anova_lm(model)

# F-value, P-value
# 1. 2.370578, 0.114943
# 2. 0.720381, 0.549614 
# 3. 2.308081, 0.066915

                          df       sum_sq     mean_sq         F    PR(>F)
Decoration_Type          2.0  1764.500000  882.250000  2.370578  0.114943
Region                   3.0   804.305556  268.101852  0.720381  0.549614
Decoration_Type:Region   6.0  5153.944444  858.990741  2.308081  0.066915
Residual                24.0  8932.000000  372.166667       NaN       NaN

### ❌ 로지스틱 회귀 2단계

고객 정보를 나타낸 데이터이다. 주어진 데이터에서 500개 중 앞에서부터 350개는 train으로, 150개는 test 데이터로 나눈다. 모델을 학습(적합)할 때는 train 데이터를 사용하고, 예측할 때는 test 데이터를 사용한다. 모델은 로지스틱 회귀를 써서 고객이 특정 제품을 구매할지 여부를 예측하되, 페널티는 부과하지 않는다.  
  
종속변수: purchase (0: 구매 안 함, 1: 구매 함)
  
1. income 변수를 독립변수로 purchase를 종속변수로 사용하여 로지스틱 회귀 모형을 만들고, income 변수가 한 단위 증가할 때 구매할 오즈비 값을 계산하시오. (반올림하여 소수 넷째자리까지 계산)
  
2. 독립변수 income만 사용해 학습한 모델에서 test 데이터의 purchase를 예측하고, accuracy (정확도)를 구하시오. (반올림하여 소수 셋째자리까지 계산)
  
3. 독립변수 income만 사용해 학습한 모델의 로짓 우도를 계산하시오.
  
4. 독립변수 income만 사용해 학습한 모델의 유의확률(p-value)를 구하시오.

In [27]:
import pandas as pd
import numpy as np
df = pd.read_csv("../data/Customer_Data.csv")

df.head()

   age  income  marital_status  children  gender  purchase
0   62  111980               1         2       1         0
1   65  107314               0         3       1         0
2   18   56209               1         1       1         1
3   21   28010               1         3       0         1
4   21   79618               0         2       0         1

In [28]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from sklearn.metrics import accuracy_score

df = pd.read_csv("../data/Customer_Data.csv")

train = df[:350]
test = df[350:]  # 수정: 350~500

model1 = smf.logit("purchase ~ income", data=train).fit()

# 1. 오즈비
odds_ratio = np.exp(model1.params["income"])
print("1. 오즈비 :", round(odds_ratio, 4))

# 2. 정확도
pred_prob = model1.predict(test)
pred_class = (pred_prob >= 0.5).astype(int)
acc = accuracy_score(test["purchase"], pred_class)
print("2. 정확도 :", round(acc, 3))

# 3. 로그 우도 (log-likelihood)
print("3. 로그 우도 :", round(model1.llf, 4))

# 4. p-value (income 변수)
print("4. p-value :", round(model1.pvalues["income"], 4))

Optimization terminated successfully.
         Current function value: 0.692599
         Iterations 3
1. 오즈비 : 1.0
2. 정확도 : 0.507
3. 로그 우도 : -242.4098
4. p-value : 0.5965

### ❌ 잔차이탈도 : -2 × (현재 fitted model의 log-likelihood)

#### 잔차이탈도를 구하시오  
고객 정보를 나타낸 데이터이다. 주어진 데이터에서 500개 중 앞에서부터 300개는 train으로, 200개는 test 데이터로 나눈다. 모델을 학습(적합)할 때는 train 데이터를 사용하고, 예측할 때는 test 데이터를 사용한다. 모델은 로지스틱 회귀를 써서 고객이 특정 제품을 구매할지 여부를 예측하되, 페널티는 부과하지 않는다.  
  
종속변수: purchase (0: 구매 안 함, 1: 구매 함)  

Q. age, income, marital_status 변수를 독립변수로 purchase를 종속변수로 사용하여 로지스틱 회귀 모형을 만들고, 잔차이탈도를 구하시오. (반올림하여 소수 넷째자리까지 계산)

In [29]:
import pandas as pd
df = pd.read_csv("../data/Customer_Data.csv")

df.head()

   age  income  marital_status  children  gender  purchase
0   62  111980               1         2       1         0
1   65  107314               0         3       1         0
2   18   56209               1         1       1         1
3   21   28010               1         3       0         1
4   21   79618               0         2       0         1

In [30]:
train = df[:300]
test = df[300:]

import statsmodels.formula.api as smf
model = smf.logit("purchase ~ age + income + marital_status", data = train).fit()
print("잔차 이탈도 :", round(-2 * model.llf, 4))

Optimization terminated successfully.
         Current function value: 0.687415
         Iterations 4
잔차 이탈도 : 412.449

#### 로지스틱 회귀 모델의 AIC와 BIC 계산
독립변수(Pregnancies, BMI, DiabetesPedigreeFunction)를 사용하여 로지스틱 회귀 모델을 학습하고, 학습된 모델의 AIC와 BIC 값을 계산하세요.(종속변수는 Outcome)  
  
1. 모델의 로그 우도(Log-Likelihood)를 기반으로 AIC와 BIC 값을 계산하세요.
2. Pregnancies를 범주형 변수로 처리하여 로지스틱 회귀 모델을 학습하세요.  
    (독립변수(Pregnancies, BMI, DiabetesPedigreeFunction)를 사용)  
    모델의 로그 우도(Log-Likelihood)를 구하시오

In [31]:
import pandas as pd
df = pd.read_csv("../data/diabetes_train.csv")
df.head()

,id,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,377,1,87,60,37,75,37.2,0.509,22,0
1,370,3,173,82,48,465,38.4,2.137,25,1
2,408,8,197,74,0,0,25.9,1.191,39,1
3,535,4,132,0,0,0,32.9,0.302,23,1
4,691,13,158,114,0,0,42.3,0.257,44,1

In [32]:
import statsmodels.formula.api as smf
model1 = smf.logit("Outcome ~ Pregnancies + BMI + DiabetesPedigreeFunction", data = df).fit()
print("1. AIC :", model1.aic, ", BIC :", model1.bic)

Optimization terminated successfully.
         Current function value: 0.549382
         Iterations 6
1. AIC : 640.8879324373285 , BIC : 658.312363080112

In [33]:
model2 = smf.logit("Outcome ~ C(Pregnancies) + BMI + DiabetesPedigreeFunction", data = df).fit()
print("2. 모델의 로그 우도 :", model2.llf)

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.528387
         Iterations: 35
2. 모델의 로그 우도 : -304.3508403850429

d:\공부\자격증\빅데이터분석기사\venv\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

### 다중 선형회귀

1. 모든 변수를 사용하여 OLS 모델을 적합하고, 회귀계수 중 가장 큰 값은?
2. 유의미하지 않은 변수를 제거한 후 모델을 다시 적합하고, 회귀계수 중 가장 작은 변수명은?
3. 2번 모델의 R-squared 값을 계산하고 해석하세요.
4. ❌ 1번 모델에서 새로운 데이터(x1=5, x2=12, x3=10, x4=3)에 대해 y 값을 예측하세요.
5. 1번 모델에서 x1, x2, x3, x4의 상관관계를 계산하고 가장 큰 상관계수를 구하시오. (단, 자기 상관관계 제외)
6. x1과 x2만을 예측 변수로 사용하는 모델을 적합하고, 전체 모델과 R-squared 값을 구하시오.
7. ❌ 잔차(residual) 분석을 수행하고, 잔차의 표준편차를 구하시오.
8. ❌ 1번 모델에서 새로운 데이터(x1=5, x2=12, x3=10, x4=3)에 대해 y의 신뢰구간 하한(97% 신뢰수준)을 구하세요.
9. ❌ 1번 모델에서 새로운 데이터(x1=5, x2=12, x3=10, x4=3)에 대해 y의 예측구간 상한(97% 신뢰수준)을 구하세요.

In [34]:
import pandas as pd
df = pd.read_csv("../data/t3_regression_data.csv")
df.head()

         x1         x2         x3        x4          y
0  1.354882  13.660146  12.025720  2.265464 -10.090372
1  8.878517  12.798070  14.194644  4.694667   7.798310
2  9.326056  18.815027   9.817460  2.519119  -2.287519
3  4.455682  11.667165   7.402825  4.801164  -1.945564
4  3.882355  11.008464  14.603228  3.360569   1.628605

In [35]:
import statsmodels.formula.api as smf
model1 = smf.ols("y ~ x1 + x2 + x3 + x4", data = df).fit()
print(model.summary())

print("1. 회귀계수 중 가장 큰 값 :", model1.params.max())

                           Logit Regression Results
==============================================================================
Dep. Variable:               purchase   No. Observations:                  300
Model:                          Logit   Df Residuals:                      296
Method:                           MLE   Df Model:                            3
Date:                Thu, 18 Jun 2026   Pseudo R-squ.:                0.007474
Time:                        00:43:38   Log-Likelihood:                -206.22
converged:                       True   LL-Null:                       -207.78
Covariance Type:            nonrobust   LLR p-value:                    0.3756
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.3407      0.452      0.753      0.451      -0.546       1.227
age               -0.0094      0.008     -1.236      0.216      -0.024       0.005
income          3.636e-06   4.02e-06      0.904      0.366   -4.25e-06    1.15e-05
marital_status    -0.2192      0.235     -0.931      0.352      -0.680       0.242
==================================================================================
1. 회귀계수 중 가장 큰 값 : 2.9815890614775196

In [36]:
model2 = smf.ols("y ~ x1 + x2 + x3", data = df).fit()
print(model2.summary())

print("2. 회귀계수 중 가장 작은 변수 명 :", model2.params.idxmin())
print("3. R-squared :", model2.rsquared)

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.988
Model:                            OLS   Adj. R-squared:                  0.988
Method:                 Least Squares   F-statistic:                     2672.
Date:                Thu, 18 Jun 2026   Prob (F-statistic):           2.55e-92
Time:                        00:43:38   Log-Likelihood:                -130.91
No. Observations:                 100   AIC:                             269.8
Df Residuals:                      96   BIC:                             280.2
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.0628      0.667      4.589      0.000       1.738       4.388
x1             1.9986      0.030     67.020      0.000       1.939       2.058
x2            -1.4942      0.033    -45.529      0.000      -1.559      -1.429
x3             0.4636      0.033     13.923      0.000       0.398       0.530
==============================================================================
Omnibus:                        2.285   Durbin-Watson:                   1.931
Prob(Omnibus):                  0.319   Jarque-Bera (JB):                1.836
Skew:                           0.324   Prob(JB):                        0.399
Kurtosis:                       3.140   Cond. No.                         138.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
2. 회귀계수 중 가장 작은 변수 명 : x2
3. R-squared : 0.9881643592045125

In [37]:
new = pd.DataFrame({
    "x1": [5],
    "x2": [12],
    "x3": [10],
    "x4": [3]
})

print("4. 1번 모델에서 새로운 데이터(x1=5, x2=12, x3=10, x4=3)에 대해 y 값을 예측 :", model1.predict(new)[0])

4. 1번 모델에서 새로운 데이터(x1=5, x2=12, x3=10, x4=3)에 대해 y 값을 예측 : -0.2433084582017389

In [38]:
print("5. 1번 모델에서 x1, x2, x3, x4의 상관관계를 계산하고 가장 큰 상관계수를 구하시오. (단, 자기 상관관계 제외) :", df.corr())

5. 1번 모델에서 x1, x2, x3, x4의 상관관계를 계산하고 가장 큰 상관계수를 구하시오. (단, 자기 상관관계 제외) :           x1        x2        x3        x4         y
x1  1.000000 -0.115152  0.080456  0.117670  0.822594
x2 -0.115152  1.000000 -0.164049 -0.224881 -0.627445
x3  0.080456 -0.164049  1.000000  0.075652  0.301941
x4  0.117670 -0.224881  0.075652  1.000000  0.218884
y   0.822594 -0.627445  0.301941  0.218884  1.000000

In [39]:
model2 = smf.ols("y ~ x1 + x2", data = df).fit()
print("6. R-squared :", model2.rsquared)

6. R-squared : 0.9642665748957848

In [40]:
# 7. ❌ 잔차 분석 수행
print("7. 잔차의 표준편차 : ", model1.resid.std())

7. 잔차의 표준편차 :  0.9001841451852483

In [41]:
# 8. 신뢰구간 하한 (97%)
pred_summary = model1.get_prediction(new).summary_frame(alpha=0.03)
print("8. 신뢰구간 하한 (97%):", round(pred_summary["mean_ci_lower"][0], 4))

8. 신뢰구간 하한 (97%): -0.5402

In [42]:
# 9. 예측구간 상한 (97%)
print("9. 예측구간 상한 (97%):", round(pred_summary["obs_ci_upper"][0], 4))

9. 예측구간 상한 (97%): 1.8029

#### ❌ 베스킨라빈스는 쿼트(Quart) 아이스크림의 중앙값이 620g이라고 주장하고 있습니다. 
저는 실제로 이 아이스크림의 중앙값이 620g보다 무겁다고 주장합니다. 다음은 20개의 쿼트 아이스크림 샘플의 무게 측정 결과입니다. 이 측정 결과를 바탕으로 나의 주장이 사실인지 비모수 검정(Wilcoxon Signed-Rank Test)을 통해 검정해보십시오. p-value값을 반올림하여 소수점 둘째 자리까지 계산  
  
귀무가설: "베스킨라빈스 쿼트 아이스크림의 중앙값은 620g이다."  
대립가설: "베스킨라빈스 쿼트 아이스크림의 중앙값은 620g보다 무겁다."

In [43]:
import pandas as pd
data = {
    "weight": [630, 610, 625, 615, 622, 618, 623, 619, 620, 624, 616, 621, 617, 629, 626, 620, 618, 622, 625, 615, 
               628, 617, 624, 619, 621, 623, 620, 622, 618, 625, 616, 629, 620, 624, 617, 621, 623, 619, 625, 618,
               622, 620, 624, 617, 621, 623, 619, 625, 618, 622]
}
df = pd.DataFrame(data)
df.head()

   weight
0     630
1     610
2     625
3     615
4     622

In [44]:
median = 620

statistic, p_value = stats.wilcoxon(df["weight"] - median, alternative='greater')

if p_value < 0.05: print("H0 기각")
else: print("H0 채택")

H0 기각